// PACKMAN_0800.c
// Generated by decompiling PACKMAN.EXE
// using Reko decompiler version 0.10.0.0.

#include "PACKMAN.h"

Eq_3 g_t8000 = // 00008000
	{
		null
	};
// 0800:0100: void fn0800_0100(Register Eq_3 si, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds)
void fn0800_0100(Eq_3 si, struct Eq_6 * es, struct Eq_7 * ds)
{
	seg0800->t019D = cs;
	ui16 bp_8 = ds->w0002;
	word16 bx_9 = ds->w002C;
	*((word16) cs + 0x00006FF2) = es;
	*((word16) cs + 0x00006FF4) = bx_9;
	*((word16) cs + 0x00006FF0) = bp_8;
	uint16 bp_16 = bp_8 - cs;
	cu16 di_17 = *((word16) cs + 41150);
	if (di_17 < 0x0100)
	{
		*((word16) cs + 41150) = 0x0100;
		di_17 = 0x0100;
	}
	uint16 di_29 = (di_17 + 0xA3C8 + *((word16) cs + 41148) >> 0x04) + 0x01;
	if (*((word16) cs + 41150) == 0x00 || *((word16) cs + 41148) == 0x00)
	{
		di_29 = 0x1000;
		if (bp_16 <= 0x1000)
			di_29 = bp_16;
	}
	uint16 bx_45 = (word16) cs + di_29;
	*((word16) cs + 28648) = bx_45;
	*((word16) cs + 28652) = bx_45;
	__cli();
	__sti();
	struct Eq_67 * es_58 = seg0800->t019D;
	Eq_3 di_59 = 0xA0C6;
	word16 cx_61;
	for (cx_61 = 770; cx_61 != 0x00; --cx_61)
	{
		es_58->*di_59 = 0x00;
		di_59 = (word32) di_59 + 1;
	}
	fn0800_01CE(si, di_59, cs);
}

// 0800:018D: Register (ptr16 Eq_90) fn0800_018D()
// Called from:
//      fn0800_0100
//      fn0800_68BC
struct Eq_90 * fn0800_018D()
{
	fnF000_E05B();
	return seg0800->t019D;
}

// 0800:019F: Register Eq_3 fn0800_019F(Register Eq_3 si, Register Eq_3 di, Register Eq_3 ds)
// Called from:
//      fn0800_01CE
Eq_3 fn0800_019F(Eq_3 si, Eq_3 di, Eq_3 ds)
{
	*((word32) ds + 41220) = 0x01;
	*((word32) ds + 41218) = 0x00;
	Eq_3 ds_29 = fn0800_3632(si, di, SEQ(ds, 0xA104), SEQ(ds, 0xA102), 0x6FF8, ds);
	*((word32) ds_29 + 41158) = 0x0F;
	*((word32) ds_29 + 41160) = 0x0D;
	return ds_29;
}

// 0800:01CE: void fn0800_01CE(Register Eq_3 si, Register Eq_3 di, Register Eq_3 ds)
// Called from:
//      fn0800_0100
void fn0800_01CE(Eq_3 si, Eq_3 di, Eq_3 ds)
{
	fn0800_6DBC(&Eq_4483::t1460);
	fn0800_0BDC(fn0800_019F(si, di, ds));
}

// 0800:0215: void fn0800_0215(Register Eq_3 ds, Stack word16 wArg02, Stack Eq_139 bArg04, Stack word16 wArg06)
// Called from:
//      fn0800_05E9
//      fn0800_06F3
//      fn0800_0BDC
void fn0800_0215(Eq_3 ds, word16 wArg02, Eq_139 bArg04, word16 wArg06)
{
	fn0800_4A0B((byte) wArg04);
	fn0800_3BBE(0x00, 188, 0x0140, 200, 0x01);
	fn0800_42F6(0x00, 0x00, 0x01);
	fn0800_42B5(0x00, 0x02);
	fn0800_4BD9(wArg02, 188, SEQ(ds, wArg06));
}

// 0800:0267: void fn0800_0267(Register Eq_3 ds, Stack Eq_185 wArg02)
// Called from:
//      fn0800_111E
void fn0800_0267(Eq_3 ds, Eq_185 wArg02)
{
	Eq_186 di_101 = 0x00;
	while (di_101 < 0x0C)
	{
		ci16 si_21;
		for (si_21 = 0x00; si_21 < 0x14; ++si_21)
		{
			fn0800_6BF7(ds, (word16) (((char *) (word16) (wArg02 *32 0x01E0 + di_101 *32 0x28) + (si_21 << 0x01))[0x00006FFC] *32 0x38) + 0x8C1E, 0xA0CA, 0x38);
			fn0800_41C5(si_21 << 0x04, (word16) (di_101 *32 0x0E), SEQ(ds, 0xA0C6), 0x00);
		}
		di_101 = (word16) di_101 + 1;
	}
}

// 0800:02D6: void fn0800_02D6(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
void fn0800_02D6(Eq_3 ds)
{
	while (*((word32) ds + 37494) != 0x00)
	{
		Eq_241 bx_12 = *((word32) ds + 37494);
		Eq_241 si_13 = ds->*((word16) bx_12 + 2);
		fn0800_6D6D(ds, bx_12);
		*((word32) ds + 37494) = si_13;
	}
	((word32) ds + 0x00009278)->u0 = 0x00;
}

// 0800:02F8: void fn0800_02F8(Register Eq_3 ds, Stack (memptr Eq_3 (memptr Eq_3 code)) wArg02, Stack (memptr Eq_3 code) wArg04)
// Called from:
//      fn0800_0BDC
void fn0800_02F8(Eq_3 ds, <anonymous> Eq_3::* Eq_3::* wArg02, <anonymous> Eq_3::* wArg04)
{
	if (wArg02 == 0x00)
	{
		if (*((word32) ds + 0x00009278) == 0x00)
		{
			Eq_241 ax_45 = fn0800_69F0(ds, 0x04);
			*((word32) ds + 37494) = ax_45;
			*((word32) ds + 0x00009278) = ax_45;
			if (ax_45 == 0x00)
				return;
		}
		else
		{
			Eq_241 ax_23 = fn0800_69F0(ds, 0x04);
			ds->*((word32) (*((word32) ds + 0x00009278)) + 2) = ax_23;
			if (ax_23 == 0x00)
				return;
			*((word32) ds + 0x00009278) = ds->*((word32) (*((word32) ds + 0x00009278)) + 2);
		}
		Eq_241 bx_63 = *((word32) ds + 0x00009278);
		(ds->*((word16) bx_63 + 2)).u0 = 0x00;
		ds->*bx_63 = wArg04;
	}
	else
		ds->*wArg02 = wArg04;
}

// 0800:03BB: void fn0800_03BB(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
void fn0800_03BB(Eq_3 ds)
{
	Eq_241 si_10 = *((word32) ds + 37494);
	while (si_10 != 0x00)
	{
		(0x0800->*(ds->*si_10))();
		si_10 = ds->*((word16) si_10 + 2);
	}
}

// 0800:03CD: Register byte fn0800_03CD(Register (ptr16 Eq_328) es, Register Eq_3 ds, Register out ptr16 siOut, Register out ptr16 diOut, Register out (ptr16 Eq_332) dsOut)
// Called from:
//      fn0800_042B
//      fn0800_044C
byte fn0800_03CD(struct Eq_328 * es, Eq_3 ds, ptr16 & siOut, ptr16 & diOut, struct Eq_332 & dsOut)
{
	ptr16 di_28;
	struct Eq_332 * ds_29;
	siOut = fn0800_6DDA(es, ds, 22, fp - 0x12, fp - 0x12, out di_28, out ds_29);
	diOut = di_28;
	dsOut = ds_29;
	return bLoc12;
}

// 0800:03F2: void fn0800_03F2(Stack word16 wArg02)
// Called from:
//      fn0800_0419
//      fn0800_06F3
//      fn0800_0B33
void fn0800_03F2(word16 wArg02)
{
	word16 si_15 = wArg02;
	while (true)
	{
		word16 si_18 = si_15 - 0x01;
		if (si_15 == 0x00)
			break;
		word16 di_23;
		for (di_23 = 0x3C; di_23 != 0x00; --di_23)
			si_15 = si_18;
	}
}

// 0800:0419: void fn0800_0419(Stack uint16 wArg02)
// Called from:
//      fn0800_111E
void fn0800_0419(uint16 wArg02)
{
	fn0800_03F2((word16) (wArg02 *32 1000));
}

// 0800:042B: Register byte fn0800_042B(Register Eq_3 ds, Register out Eq_3 dsOut)
// Called from:
//      fn0800_06F3
byte fn0800_042B(Eq_3 ds, union Eq_3 & dsOut)
{
	do
	{
		uint16 ax_35;
		if (*((word32) ds + 0x0000927E) != 0x00 && *((word32) ds + 0x0000A112) != 0x00)
		{
			ax_35 = SEQ(ah, 0x20);
			goto l0800_044B;
		}
		struct Eq_328 * es_12;
		word16 ax_10 = fn0800_0474(out es_12);
		ah = SLICE(ax_10, byte, 8);
	} while (ax_10 == 0x00);
	word16 si_104;
	word16 di_105;
	ax_35 = (uint16) fn0800_03CD(es_12, ds, out si_104, out di_105, out ds);
l0800_044B:
	dsOut = ds;
	return (byte) ax_35;
}

// 0800:044C: Register word16 fn0800_044C(Register Eq_3 ds, Register out ptr16 siOut, Register out ptr16 diOut, Register out Eq_3 dsOut)
// Called from:
//      fn0800_0ADF
//      fn0800_0B33
word16 fn0800_044C(Eq_3 ds, ptr16 & siOut, ptr16 & diOut, union Eq_3 & dsOut)
{
	word16 ax_51;
	if (*((word32) ds + 0x0000927E) == 0x00 || *((word32) ds + 0x0000A112) == 0x00)
	{
		struct Eq_328 * es_12;
		if (fn0800_0474(out es_12) == 0x00 || (byte) ((uint16) fn0800_03CD(es_12, ds, out si, out di, out ds)) != 0x20)
		{
			ax_51 = 0x00;
l0800_0473:
			siOut = si;
			diOut = di;
			dsOut = ds;
			return ax_51;
		}
	}
	ax_51 = 0x01;
	goto l0800_0473;
}

// 0800:0474: Register word16 fn0800_0474(Register out (ptr16 Eq_386) esOut)
// Called from:
//      fn0800_042B
//      fn0800_044C
word16 fn0800_0474(struct Eq_386 & esOut)
{
	word16 ax_14;
	if (0000:041A == 0000:041C)
		ax_14 = 0x00;
	else
		ax_14 = 0x01;
	esOut = 0x00;
	return ax_14;
}

// 0800:0492: void fn0800_0492(Register Eq_3 ds)
// Called from:
//      fn0800_06F3
//      fn0800_0ADF
//      fn0800_0B33
//      fn0800_0BDC
void fn0800_0492(Eq_3 ds)
{
	0000:041A = 0000:041C;
	*((word32) ds + 0x0000A112) = 0x00;
}

// 0800:05E9: void fn0800_05E9(Register Eq_3 ds, Stack word16 wArg02, Stack Eq_139 wArg04, Stack Eq_463 wArg06)
// Called from:
//      fn0800_06F3
//      fn0800_0BDC
//      fn0800_111E
void fn0800_05E9(Eq_3 ds, word16 wArg02, Eq_139 wArg04, Eq_463 wArg06)
{
	fn0800_3EBA(0x01, 0x00);
	fn0800_6B55(ds, wArg06, 41222, 0x0A);
	fn0800_48E3(wArg02, 188, wArg02 + 0x1F, 199);
	fn0800_0215(ds, wArg02, wArg04, 41222);
}

// 0800:0635: void fn0800_0635(Register Eq_3 ds, Stack wchar_t wArg02, Stack Eq_497 bArg04, Stack word16 wArg06, Stack word16 wArg08)
// Called from:
//      fn0800_06F3
//      fn0800_0ADF
//      fn0800_0B33
void fn0800_0635(Eq_3 ds, wchar_t wArg02, Eq_497 bArg04, word16 wArg06, word16 wArg08)
{
	fn0800_4A0B((byte) wArg04);
	fn0800_42F6(0x00, 0x00, wArg06);
	fn0800_42B5(0x01, 0x02);
	fn0800_3BBE(0x00, wArg02, 0x0140, wArg02 + 0x07, 0x01);
	fn0800_4BD9(0xA0, wArg02, SEQ(ds, wArg08));
}

// 0800:06F3: Register Eq_3 fn0800_06F3(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
Eq_3 fn0800_06F3(Eq_3 ds)
{
	fn0800_0492(ds);
	fn0800_3EBA(0x01, 0x00);
	fn0800_48E3(0x00, 0x00, 0x013F, 199);
	fn0800_0635(ds, 0x00, 0x03, 0x04, 39003);
	fn0800_0635(ds, 0x28, 0x02, 0x01, ~0x6668);
	Eq_550 si_107 = 0x00;
	while (si_107 < 11)
	{
		fn0800_0635(ds, (word16) (si_107 *32 0x0A) + 0x46, 0x03, 0x01, SEQ(ds, 38686)[si_107 * 0x02]);
		si_107 = (word16) si_107 + 1;
	}
	if (*((word32) ds + 0x0000927E) == 0x00)
		fn0800_0215(ds, 0x00, 0x02, 38708);
	else
		fn0800_0215(ds, 0x00, 0x02, ~0x68C0);
	fn0800_0215(ds, 0x5C, 0x01, 39336);
l0800_07CC:
	fn0800_05E9(ds, 220, 0x02, 0x09 - *((word32) ds + 37500));
	fn0800_0215(ds, 228, 0x01, ~0x6646);
	while (true)
	{
		cu8 al_285 = (byte) (uint16) fn0800_042B(ds, out ds);
		if (al_285 == 0x20)
			break;
		if (al_285 >= 0x30 && al_285 <= 0x39)
		{
			*((word32) ds + 37500) = 0x39 - (uint16) al_285;
			goto l0800_07CC;
		}
		word16 cx_342;
		word16 bx_343 = 0x081C;
		Eq_628 ax_410 = (uint16) al_285;
		for (cx_342 = 0x05; cx_342 != 0x00; --cx_342)
		{
			if (ax_410 == (seg0800->*bx_343).t0000)
			{
				(seg0800->*bx_343).t0000();
				return;
			}
			++bx_343;
		}
		fn0800_6FAB(600);
		fn0800_03F2(0x46);
		fn0800_6FD7();
	}
	fn0800_3EBA(0x01, 0x00);
	fn0800_48E3(0x00, 188, 0x013F, 199);
	return;
}

// 0800:097F: void fn0800_097F(Stack ui16 wArg02, Stack word16 wArg04, Stack Eq_663 wArg06)
// Called from:
//      fn0800_09F1
//      fn0800_0A16
void fn0800_097F(ui16 wArg02, word16 wArg04, Eq_663 wArg06)
{
	__cli();
	(&0x00->a0000->w0000)[wArg02 * 0x04] = wArg04;
	(&0x00->t0002)[wArg02] = (struct Eq_4736) wArg06;
	__sti();
}

// 0800:09BB: Register word16 fn0800_09BB(Stack ui16 wArg02, Register out Eq_663 dxOut)
// Called from:
//      fn0800_09F1
word16 fn0800_09BB(ui16 wArg02, union Eq_663 & dxOut)
{
	word16 ax_17 = (&0x00->a0000->w0000)[wArg02 * 0x04];
	dxOut = (&0x00->t0002)[wArg02];
	return ax_17;
}

// 0800:09F1: void fn0800_09F1(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
void fn0800_09F1(Eq_3 ds)
{
	Eq_663 dx_11;
	word16 ax_8 = fn0800_09BB(0x08, out dx_11);
	*((word32) ds + 41244) = dx_11;
	*((word32) ds + 0x0000A11A) = ax_8;
	fn0800_097F(0x08, 0x08D8, cs);
	*((word32) ds + 0x0000927E) = 0x01;
}

// 0800:0A16: void fn0800_0A16(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
void fn0800_0A16(Eq_3 ds)
{
	fn0800_097F(0x08, *((word32) ds + 0x0000A11A), *((word32) ds + 41244));
	*((word32) ds + 0x0000927E) = 0x00;
}

// 0800:0ADF: Register Eq_3 fn0800_0ADF(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
Eq_3 fn0800_0ADF(Eq_3 ds)
{
	fn0800_3EBA(0x01, 0x00);
	fn0800_48E3(0x00, 0x00, 0x013F, 199);
	fn0800_0635(ds, 0x50, 0x03, 0x04, ~0x6644);
	fn0800_0635(ds, 0x78, 0x01, 0x01, 0x99C5);
	fn0800_0492(ds);
	do
	{
		ds_138 = ds;
		word16 di_137;
		word16 si_136;
	} while (fn0800_044C(ds_138, out si_136, out di_137, out ds) == 0x00);
	return ds;
}

// 0800:0B33: Register Eq_3 fn0800_0B33(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
Eq_3 fn0800_0B33(Eq_3 ds)
{
	fn0800_3EBA(0x01, 0x00);
	fn0800_48E3(0x00, 0x00, 0x013F, 199);
	fn0800_0492(ds);
	ui16 si_122 = 0x00;
	ci16 wLoc06_212 = 100;
	while (true)
	{
		ci16 v12_70 = wLoc06_212 + 0x01;
		wLoc06_212 = v12_70;
		if (v12_70 >= 100)
		{
			fn0800_0635(ds, 0x3C, SEQ(ds, 38732)[si_122 * 0x02], 0x04, 0x99D4);
			wLoc06_212 = 0x00;
		}
		Eq_652 di_119;
		if (fn0800_044C(ds, out si_122, out di_119, out ds) != 0x00)
			break;
		if (di_119 < 600 || di_119 > 900)
			;
		if (*((word32) ds + 0x0000A114) != 0x00)
			fn0800_6FAB(di_119);
		fn0800_03F2(0x03);
	}
	fn0800_6FD7();
	return ds;
}

// 0800:0BDC: void fn0800_0BDC(Register Eq_3 ds)
// Called from:
//      fn0800_01CE
void fn0800_0BDC(Eq_3 ds)
{
	0000:007C = (word16 *) 0x9280;
	0000:007E = (union Eq_3 *) ds;
	fn0800_09F1(ds);
	fn0800_0A16(ds);
	((word32) ds + 0x0000A122)->u0 = 0x00;
	while (true)
	{
		Eq_3 ds_46 = fn0800_06F3(ds);
		((word32) ds_46 + 0x0000A118)->u0 = 0x00;
		fn0800_0492(ds_46);
		((word32) ds_46 + 0x0000A11E)->u0 = 0x23;
		*((word32) ds_46 + 0x0000A114) = 0x01;
		((word32) ds_46 + 0x0000A11E)->u0 = (int16) ((int32) *((word32) ds_46 + 0x0000A11E) /16 0x07);
		fn0800_02F8(ds_46, 0x00, 0x0A2F);
		fn0800_02F8(ds_46, 0x00, 0x13EE);
		fn0800_02F8(ds_46, 0x00, 3939);
		fn0800_02F8(ds_46, 0x00, 0x12B7);
		fn0800_02F8(ds_46, 0x00, 4344);
		((word32) ds_46 + 0x0000A116)->u0 = 0x00;
		while (*((word16) ds_46 + 0x0000A116) < *((word16) ds_46 + 28666))
		{
			fn0800_05E9(ds_46, 0x2D, 0x03, *((word16) ds_46 + 0x0000A118));
			fn0800_05E9(ds_46, 0xBA, 0x02, *((word16) ds_46 + 0x0000A122));
			fn0800_0215(ds_46, 0x00, 0x03, ~0x6622);
			fn0800_0215(ds_46, 0x82, 0x02, 39395);
			fn0800_0215(ds_46, 0xFA, 0x03, ~0x6614);
			fn0800_111E(ds_46);
			fn0800_6FD7();
			while (*((word32) ds_46 + 0x0000A380) == 0x00)
				fn0800_03BB(ds_46);
			fn0800_05E9(ds_46, 0xBA, 0x02, *((word32) ds_46 + 0x0000A122));
			if (*((word32) ds_46 + 0x0000A11E) < 0x00)
				break;
			if (*((word32) ds_46 + 0x0000A380) == 0x02)
				--*((word32) ds_46 + 0x0000A116);
			*((word32) ds_46 + 0x0000A116) = (word32) *((word32) ds_46 + 0x0000A116) + 1;
		}
		fn0800_02D6(ds_46);
		if (*((word16) ds_46 + 0x0000A11E) >= 0x00)
			ds = fn0800_0B33(ds_46);
		else
			ds = fn0800_0ADF(ds_46);
	}
}

// 0800:111E: void fn0800_111E(Register Eq_3 ds)
// Called from:
//      fn0800_0BDC
void fn0800_111E(Eq_3 ds)
{
	fn0800_0267(ds, *((word32) ds + 0x0000A116));
	fn0800_05E9(ds, 0x0136, 0x02, *((word32) ds + 0x0000A11E));
	fn0800_0419(0x02);
	*((word32) ds + 0x0000A19C) = 0x00;
	*((word32) ds + 0x0000A380) = 0x00;
	*((word32) ds + 0x0000927A) = 0x00;
	fn0800_6BF7(ds, (word16) (*((word32) ds + 0x0000A116) *32 0x01E0) + 28668, 41374, 0x01E0);
	*((word32) ds + 41854) = 0x00;
	ci16 di_118;
	word16 wLoc04_314 = 41374;
	for (di_118 = 0x00; di_118 < 0xF0; ++di_118)
	{
		if (ds->*wLoc04_314 == 0x01)
			++*((word32) ds + 41854);
		++wLoc04_314;
	}
	*((word32) ds + 41248) = (int16) ((word32) (word16) (*((word32) ds + 0x0000A116) *32 0x03) /16 *((word32) ds + 28666)) + 0x02;
	int16 di_133;
	word16 si_139 = 41282;
	for (di_133 = 0x01; di_133 < *((word32) ds + 41248); ++di_133)
	{
		(ds->*si_139).w0000 = 300;
		(ds->*si_139).w0002 = 0x54;
		(ds->*si_139).w000A = 0x04;
		ui16 dx_215 = ((int16) ((word32) fn0800_6F53(ds) % 0x03) << 0x05) + 0x9680;
		(ds->*si_139).w0006 = dx_215;
		(ds->*si_139).w0004 = dx_215;
		(ds->*si_139).w0008 = 0x20;
		(ds->*si_139).w0012 = (int16) ((word32) fn0800_6F53(ds) % (*((word32) ds + 37500) + 0x04)) + (word16) (*((word32) ds + 37500) *32 0x0E) + 0x04;
		(ds->*si_139).w000E = (ds->*si_139).w0012 << 0x01;
		(ds->*si_139).w0016 = (int16) ((word32) fn0800_6F53(ds) % (*((word32) ds + 37500) + 0x04)) + (word16) (*((word32) ds + 37500) *32 0x0E) + 0x02;
		fn0800_128C(ds, si_139, 0x9700, 0x04);
		++si_139;
	}
	*((word32) ds + 41252) = 0x04;
	*((word32) ds + 41254) = 0x54;
	*((word32) ds + 41262) = 0x02;
	cui16 ax_152 = (word16) (*((word32) ds + 37500) *32 0x0E);
	*((word32) ds + 0x0000A136) = ax_152 + 0x04;
	*((word32) ds + 41266) = ax_152 + 0x04 << 0x01;
	*((word32) ds + 0x0000A13A) = (word16) (*((word32) ds + 37500) *32 0x0E) + 0x02;
	fn0800_128C(ds, 41252, 38632, 0x04);
}

// 0800:128C: void fn0800_128C(Register Eq_3 ds, Stack (memptr Eq_3 Eq_1024) wArg02, Stack word16 wArg04, Stack word16 wArg06)
// Called from:
//      fn0800_111E
void fn0800_128C(Eq_3 ds, struct Eq_1024 Eq_3::* wArg02, word16 wArg04, word16 wArg06)
{
	(ds->*wArg02).w001A = wArg04;
	(ds->*wArg02).w0018 = wArg04;
	(ds->*wArg02).w001C = (int16) ((int32) wArg06 /16 0x02);
	(ds->*wArg02).w0014 = 0x01;
	(ds->*wArg02).w0010 = 0x01;
	(ds->*wArg02).w000C = 0x01;
}

// 0800:2D00: void fn0800_2D00(Stack Eq_3 ptrArg02, Stack Eq_3 ptrArg06)
// Called from:
//      fn0800_3632
void fn0800_2D00(Eq_3 ptrArg02, Eq_3 ptrArg06)
{
	struct Eq_1199 * ds_46 = SLICE(ptrArg02, selector, 16);
	byte Eq_1199::* si_21 = (word16) ptrArg02;
	struct Eq_1203 * es_48 = SLICE(ptrArg06, selector, 16);
	byte Eq_1203::* di_26 = (word16) ptrArg06;
	do
	{
		byte al_23 = ds_46->*si_21;
		es_48->*di_26 = al_23;
		++si_21;
		++di_26;
	} while (al_23 != 0x00);
}

// 0800:2D1F: Register int16 fn0800_2D1F(Stack word16 wArg02, Stack segptr32 ptrArg04, Stack segptr32 ptrArg08)
// Called from:
//      fn0800_30B4
int16 fn0800_2D1F(word16 wArg02, segptr32 ptrArg04, segptr32 ptrArg08)
{
	struct Eq_1224 * ds_54 = SLICE(ptrArg08, selector, 16);
	struct Eq_1226 Eq_1224::* si_24 = (word16) ptrArg08;
	struct Eq_1228 * es_56 = SLICE(ptrArg04, selector, 16);
	struct Eq_1230 Eq_1228::* di_27 = (word16) ptrArg04;
	word16 cx_21 = wArg02;
	while (cx_21 != 0x00)
	{
		++si_24;
		++di_27;
		--cx_21;
		if ((ds_54->*si_24).b0000 == (es_56->*di_27).b0000)
			return (int16) ((ds_54->*si_24).bFFFFFFFF - (es_56->*di_27).bFFFFFFFF);
	}
	return (int16) ((ds_54->*si_24).bFFFFFFFF - (es_56->*di_27).bFFFFFFFF);
}

// 0800:2D63: void fn0800_2D63(Stack Eq_3 ptrArg02)
// Called from:
//      fn0800_3632
void fn0800_2D63(Eq_3 ptrArg02)
{
	struct Eq_1257 * es_47 = SLICE(ptrArg02, selector, 16);
	byte Eq_1257::* di_24 = (word16) ptrArg02;
	word16 cx_16 = ~0x00;
	while (cx_16 != 0x00)
	{
		di_24 = di_70 + 1;
		--cx_16;
		di_70 = di_24;
		if (es_47->*di_70 != 0x00)
			return;
	}
}

// 0800:2D7E: void fn0800_2D7E(Stack segptr32 ptrArg02, Stack Eq_3 ptrArg06, Stack Eq_1277 ptrArg0A)
// Called from:
//      fn0800_33E3
//      fn0800_3454
//      fn0800_42F6
void fn0800_2D7E(segptr32 ptrArg02, Eq_3 ptrArg06, Eq_1277 ptrArg0A)
{
	struct Eq_1278 * ds_20 = SLICE(ptrArg06, selector, 16);
	Eq_1280 si_22 = (word16) ptrArg06;
	struct Eq_1282 * es_77 = SLICE(ptrArg0A, selector, 16);
	byte Eq_1282::* di_33 = (word16) ptrArg0A;
	if ((ds_20 | si_22) != 0x00)
	{
		do
		{
			byte al_30 = ds_20->*si_22;
			es_77->*di_33 = al_30;
			si_22 = (word16) si_22 + 1;
			++di_33;
		} while (al_30 != 0x00);
		--di_33;
	}
	struct Eq_1289 * ds_79 = SLICE(ptrArg02, selector, 16);
	byte Eq_1289::* si_49 = (word16) ptrArg02;
	do
	{
		byte al_51 = ds_79->*si_49;
		es_77->*di_33 = al_51;
		++si_49;
		++di_33;
	} while (al_51 != 0x00);
}

// 0800:2DAC: void fn0800_2DAC()
// Called from:
//      fn0800_2FEC
void fn0800_2DAC()
{
}

// 0800:2DBC: void fn0800_2DBC()
// Called from:
//      fn0800_2DC5
//      fn0800_2E0C
//      fn0800_3454
//      fn0800_42F6
void fn0800_2DBC()
{
}

// 0800:2DC5: Register word16 fn0800_2DC5(Register Eq_3 ds, Stack (ptr32 word16) ptrArg04)
// Called from:
//      fn0800_33E3
word16 fn0800_2DC5(Eq_3 ds, word16 * ptrArg04)
{
	word16 ax_45;
	if (!C)
		ax_45 = ~0x02;
	else
	{
		*((word32) ds + 0x00009D63) = 0x3D00;
		if (Test(UGE,false) && (true && (true && false)))
		{
			*ptrArg04 = 0x4202;
			ax_45 = 0x00;
		}
		else
		{
			fn0800_2DBC();
			ax_45 = wArg02;
		}
	}
	return ax_45;
}

// 0800:2E0C: Register word16 fn0800_2E0C(Register Eq_3 ds)
// Called from:
//      fn0800_3454
//      fn0800_42F6
word16 fn0800_2E0C(Eq_3 ds)
{
	word16 ax_28;
	if (Test(UGE,false) && Test(UGE,false))
		ax_28 = 0x00;
	else
	{
		fn0800_2DBC();
		*((word32) ds + 39942) = ~0x0B;
		ax_28 = 0x01;
	}
	return ax_28;
}

// 0800:2E45: void fn0800_2E45(Stack Eq_3 ptrArg02, Stack Eq_3 ptrArg06, Stack Eq_3 wArg0A)
// Called from:
//      fn0800_3632
void fn0800_2E45(Eq_3 ptrArg02, Eq_3 ptrArg06, Eq_3 wArg0A)
{
	struct Eq_1361 * ds_51 = SLICE(ptrArg06, selector, 16);
	byte Eq_1361::* si_43 = (word16) ptrArg06;
	struct Eq_1365 * es_53 = SLICE(ptrArg02, selector, 16);
	byte Eq_1365::* di_46 = (word16) ptrArg02;
	Eq_3 cx_24;
	for (cx_24 = wArg0A; cx_24 != 0x00; --cx_24)
	{
		es_53->*di_46 = ds_51->*si_43;
		++si_43;
		++di_46;
	}
}

// 0800:2FEC: Register Eq_3 fn0800_2FEC(Register Eq_3 ds)
// Called from:
//      fn0800_3542
Eq_3 fn0800_2FEC(Eq_3 ds)
{
	if (*((word32) ds + 0x00009C19) != 0x00)
		fn0800_2DAC();
	else
		fn0800_2DAC();
	return fn0800_6D94(ds, ~0x00);
}

// 0800:3010: Register word16 fn0800_3010(Register Eq_3 ds, Stack Eq_3 ptrArg02, Stack Eq_3 wArg06)
// Called from:
//      fn0800_3454
//      fn0800_3632
//      fn0800_42F6
word16 fn0800_3010(Eq_3 ds, Eq_3 ptrArg02, Eq_3 wArg06)
{
	Eq_3 dx_16;
	Eq_241 ax_13 = fn0800_6DAC(ds, wArg06, out dx_16);
	cui16 cx_24 = ax_13 | dx_16;
	if (cx_24 != 0x00 && (ax_13 == 0x00 && ds == dx_16))
	{
		cx_24 = 0x00;
		&dx_16.u0->t0000 = 0x00;
	}
	*ptrArg02 = ax_13;
	*((word32) ptrArg02 + 2) = dx_16;
	word16 ax_49 = 0x01;
	if (cx_24 != 0x00)
		ax_49 = 0x00;
	return ax_49;
}

// 0800:3042: void fn0800_3042(Register Eq_3 ds, Stack Eq_3 ptrArg02, Stack Eq_3 wArg06)
// Called from:
//      fn0800_3172
//      fn0800_3454
//      fn0800_3632
//      fn0800_3B02
//      fn0800_42F6
void fn0800_3042(Eq_3 ds, Eq_3 ptrArg02, Eq_3 wArg06)
{
	if ((*ptrArg02 | *((word32) ptrArg02 + 2)) != 0x00 && wArg06 != 0x00)
		fn0800_6DA0(ds, *ptrArg02);
	&((word32) ptrArg02 + 2)->u0->t0000 = 0x00;
	*ptrArg02 = 0x00;
}

// 0800:3078: Register word16 fn0800_3078(Stack word16 wArg02, Stack (ptr32 word16) ptrArg04, Stack word16 wArg08, Stack word16 wArg0A, Register out (ptr16 Eq_1468) dxOut)
// Called from:
//      fn0800_30B4
//      fn0800_3172
word16 fn0800_3078(word16 wArg02, word16 * ptrArg04, word16 wArg08, word16 wArg0A, struct Eq_1468 & dxOut)
{
	cu16 si_19 = wArg08 + *ptrArg04;
	*ptrArg04 -= si_19 & 0x0F;
	struct Eq_1468 * dx_28 = wArg0A + (si_19 >> 0x04);
	Eq_1487 si_29 = si_19 & 0x0F;
	if ((si_19 & 0x0F) != 0x00)
	{
		word16 cx_33;
		byte Eq_1468::* di_39 = Eq_1468::a0000;
		for (cx_33 = wArg02; cx_33 != 0x00; --cx_33)
		{
			dx_28->*di_39 = dx_28->*si_29;
			si_29 = (word16) si_29 + 1;
			++di_39;
		}
	}
	dxOut = dx_28;
	return 0x00;
}

// 0800:30B4: Register Eq_1511 fn0800_30B4(Stack Eq_1512 ptrArg04)
// Called from:
//      fn0800_3454
//      fn0800_6DBC
Eq_1511 fn0800_30B4(Eq_1512 ptrArg04)
{
	word16 wArg04_160 = (word16) ptrArg04;
	word16 wArg06_172 = SLICE(ptrArg04, word16, 16);
	Eq_1511 ax_129;
	<type-error> Eq_1520::* bx_19 = (word16) ptrArg04;
	struct Eq_1520 * es_21 = SLICE(ptrArg04, selector, 16);
	struct Eq_1522 * ptrLoc06_161 = &(es_21->*((char *) bx_19 + 0x0080));
	if (Mem23[0800:9C19:word16] != 0x03)
	{
		if (*ptrArg04 != 0x6B70)
		{
			Mem134[0800:9C06:word16] = ~0x03;
			ax_129.u0 = ~0x03;
			return ax_129;
		}
		if (ptrLoc06_161->b0006 < 0x02 || ptrLoc06_161->b0008 > 0x01)
		{
			Mem132[0800:9C06:word16] = ~0x11;
			ax_129.u0 = ~0x11;
			return ax_129;
		}
		Eq_1511 si_36 = 0x00;
		while (si_36 < Mem41[0800:9C56:word16])
		{
			if (fn0800_2D1F(0x08, (word16) (si_36 *32 0x1A) + 40033, &(es_21->*((char *) bx_19 + 0x008B))) == 0x00)
			{
				word16 dx_103;
				word16 ax_100 = fn0800_3078((&(es_21->*((char *) bx_19 + 0x0080)))[4], &(es_21->*((char *) bx_19 + 0x0080)), wArg04_160, wArg06_172, out dx_103);
				struct Eq_1592 Eq_3::* ax_119 = (word16) (si_36 *32 0x1A);
				(seg0800->*ax_119).w9C70 = dx_103;
				(seg0800->*ax_119).w9C6E = ax_100;
				Mem128[0800:9C06:word16] = 0x00;
				ax_129 = si_36;
				return ax_129;
			}
			si_36 = (word16) si_36 + 1;
		}
	}
	Mem137[0800:9C06:word16] = ~0x0A;
	ax_129.u0 = ~0x0A;
	return ax_129;
}

// 0800:3172: Register uint16 fn0800_3172(Stack (ptr32 word16) ptrArg04)
// Called from:
//      fn0800_42F6
uint16 fn0800_3172(word16 * ptrArg04)
{
	word16 wArg06_225 = SLICE(ptrArg04, word16, 16);
	word16 wArg04_231 = (word16) ptrArg04;
	uint16 ax_167;
	if (*ptrArg04 == 0x4B50)
	{
		struct Eq_1621 * es_191 = SLICE(ptrArg04, selector, 16);
		struct Eq_1623 Eq_1621::* di_192 = (word16) ptrArg04;
		word16 cx_27 = ~0x00;
		while (cx_27 != 0x00)
		{
			++di_192;
			--cx_27;
			if ((es_191->*di_192).b0000 != 0x1A)
				break;
		}
		struct Eq_1627 * ptrLoc10_202 = &&(es_191->*(es_191->*di_192).b0000);
		if (ptrLoc10_202->b0008 >= 0x01 && ptrLoc10_202->b000A <= 0x01)
		{
			word16 wLoc08_205 = 39535;
			uint16 wLoc06_206;
			struct Eq_1654 * ptrLoc0C_269 = &&(es_191->*(es_191->*(di_192 + 2)).b0000);
			for (wLoc06_206 = 0x00; wLoc06_206 < 0x14; ++wLoc06_206)
			{
				word16 ax_76 = ptrLoc0C_269->w0000;
				if (ptrLoc0C_269->w0002 == (seg0800->*wLoc08_205).w0000 && ax_76 == (seg0800->*wLoc08_205).w0000)
				{
					struct Eq_1683 Eq_3::* ax_107 = (word16) (wLoc06_206 *32 0x0F);
					fn0800_3042(seg0800, &(seg0800->*&ax_107->w9A63), (seg0800->*ax_107).t9A6B);
					(seg0800->*ax_107).w9A65 = 0x00;
					(seg0800->*ax_107).w9A63 = 0x00;
					word16 dx_154;
					word16 ax_151 = fn0800_3078(*((char *) &&(es_191->*(es_191->*di_192).b0000) + 6), &&(es_191->*(es_191->*di_192).b0000), wArg04_231, wArg06_225, out dx_154);
					(seg0800->*ax_107).w9A69 = dx_154;
					(seg0800->*ax_107).w9A67 = ax_151;
					&(seg0800->*ax_107).t9A6B.u0->t0000 = 0x00;
					ax_167 = wLoc06_206 + 0x01;
					return ax_167;
				}
				++wLoc08_205;
			}
			Mem71[0800:9C06:word16] = ~0x0A;
			ax_167 = ~0x0A;
			return ax_167;
		}
	}
	Mem173[0800:9C06:word16] = ~0x0C;
	ax_167 = ~0x0C;
	return ax_167;
}

// 0800:3359: void fn0800_3359(Register Eq_3 ds)
// Called from:
//      fn0800_3632
//      fn0800_3B02
void fn0800_3359(Eq_3 ds)
{
	&((word32) ds + 0x00009B95)->u0->t0000 = seg0800;
	*((word32) ds + 0x00009B93) = 12268;
	&((word32) ds + 0x00009B91)->u0->t0000 = seg0800;
	*((word32) ds + 39823) = 12268;
	Mem9[ds:39916:word16] = ~0x6455;
	*((word32) ds + 39924) = 0x00;
	*((word32) ds + 39922) = 0x00;
	*((word32) ds + 39946) = 0x00;
	*((word32) ds + 39944) = 0x00;
	*((word32) ds + 39928) = 0x00;
	((word32) ds + 39926)->u0 = 0x00;
	*((word32) ds + 39934) = 0x00;
	*((word32) ds + 39932) = 0x00;
	struct Eq_1736 Eq_3::* bx_18 = *((word32) ds + 39916);
	(ds->*bx_18).w000E = 0x00;
	(ds->*bx_18).w000C = 0x00;
	(ds->*bx_18).w0010 = 0x00;
	(ds->*bx_18).w0028 = 0x00;
	(ds->*bx_18).w0026 = 0x00;
	(ds->*bx_18).w002A = 0x00;
	(ds->*bx_18).b0016 = 0x00;
	*((word32) ds + 39938) = 0x01;
	*((word32) ds + 0x00009C00) = 0x01;
	*((word32) ds + 39965) = 0x00;
	*((word32) ds + 0x00009C19) = 0x00;
}

// 0800:33E3: Register word16 fn0800_33E3(Register Eq_3 ds, Stack (ptr32 word16) ptrArg04, Stack segptr32 dwArg08, Stack Eq_3 dwArg0C)
// Called from:
//      fn0800_3454
//      fn0800_42F6
word16 fn0800_33E3(Eq_3 ds, word16 * ptrArg04, segptr32 dwArg08, Eq_3 dwArg0C)
{
	word16 ax_125;
	*ptrArg04 = 0x00;
	fn0800_2D7E(dwArg08, dwArg0C, fp - 0x66);
	word16 ax_55 = fn0800_2DC5(ds, ptrArg04);
	*((word32) ds + 39942) = ax_55;
	if (ax_55 != 0x00)
	{
		fn0800_2D7E(dwArg08, 0x00, fp - 0x66);
		word16 ax_110 = fn0800_2DC5(ds, ptrArg04);
		*((word32) ds + 39942) = ax_110;
		if (ax_110 != 0x00)
		{
			ax_125 = 0x01;
			return ax_125;
		}
	}
	ax_125 = 0x00;
	return ax_125;
}

// 0800:3454: Register word16 fn0800_3454(Register Eq_3 ds, Stack Eq_3 dwArg02, Stack Eq_3 wArg06)
// Called from:
//      fn0800_3632
word16 fn0800_3454(Eq_3 ds, Eq_3 dwArg02, Eq_3 wArg06)
{
	word16 ax_201;
	fn0800_2D7E(SEQ(ds, 0xA043), SEQ(ds, (word16) (wArg06 *32 0x1A) + 40024), SEQ(ds, 0x9A01));
	struct Eq_1864 Eq_3::* ax_45 = (word16) (wArg06 *32 0x1A);
	Eq_3 dx_47 = (ds->*ax_45).t9C70;
	cui16 ax_48 = (ds->*ax_45).w9C6E;
	*((word32) ds + 0x00009B95) = dx_47;
	*((word32) ds + 0x00009B93) = ax_48;
	if ((dx_47 | ax_48) == 0x00)
	{
		if (fn0800_33E3(ds, SEQ(ds, 39930), SEQ(ds, 0x9A01), dwArg02) == 0x00)
		{
			if (fn0800_3010(ds, SEQ(ds, 39926), *((word32) ds + 39930)) != 0x00)
			{
				fn0800_2DBC();
				*((word32) ds + 39942) = ~0x04;
			}
			else
			{
				if (fn0800_2E0C(ds) == 0x00)
				{
					if (fn0800_30B4(*((word32) ds + 39926)) == wArg06)
					{
						Eq_1934 es_bx_165 = (ds->*(word16) (wArg06 *32 0x1A)).t9C6E;
						*((word32) ds + 0x00009B95) = SLICE(es_bx_165, selector, 16);
						*((word32) ds + 0x00009B93) = (word16) es_bx_165;
						fn0800_2DBC();
l0800_353A:
						ax_201 = 0x01;
						return ax_201;
					}
					fn0800_2DBC();
					*((word32) ds + 39942) = ~0x03;
				}
				fn0800_3042(ds, SEQ(ds, 39926), *((word32) ds + 39930));
			}
		}
		ax_201 = 0x00;
		return ax_201;
	}
	else
	{
		*((word32) ds + 39928) = 0x00;
		((word32) ds + 39926)->u0 = 0x00;
		&((word32) ds + 39930)->u0->t0000 = 0x00;
		goto l0800_353A;
	}
}

// 0800:3542: void fn0800_3542()
// Called from:
//      fn0800_3632
void fn0800_3542()
{
	Eq_3 ds_20 = seg0800;
	if (Mem18[0800:9C19:word16] == 0x00)
		ds_20 = fn0800_2FEC(seg0800);
	struct Eq_1959 Eq_3::* bx_38 = *((word32) ds_20 + 39914);
	fn0800_3BBE(0x00, 0x00, (ds_20->*bx_38).w0002, (ds_20->*bx_38).w0004, 0x01);
	fn0800_4A62();
	struct Eq_1976 * dx_ax_360 = (struct Eq_1976 *) <invalid>;
	struct Eq_1978 * dx_64 = SLICE(dx_ax_360, word16, 16);
	byte Eq_1978::* si_290 = (word16) dx_ax_360;
	word16 di_293 = 39995;
	word16 cx_297;
	for (cx_297 = 0x11; cx_297 != 0x00; --cx_297)
	{
		ds_20->*di_293 = dx_64->*si_290;
		++si_290;
		++di_293;
	}
	fn0800_408F(SEQ(ds_20, 39995));
	if (fn0800_4A47() != 0x01)
		fn0800_403B(0x00);
	*((word32) ds_20 + 39954) = 0x00;
	fn0800_4A0B((byte) fn0800_4A2C());
	fn0800_3F0B(SEQ(ds_20, ~0x6236), fn0800_4A2C());
	fn0800_3EBA(0x01, fn0800_4A2C());
	fn0800_3E06(0x00, 0x00, 0x01);
	fn0800_42F6(0x00, 0x00, 0x01);
	fn0800_42B5(0x00, 0x02);
	fn0800_46A1(0x00);
	fn0800_3CCF(0x00, 0x00);
}

// 0800:3632: Register Eq_3 fn0800_3632(Register Eq_3 si, Register Eq_3 di, Stack (ptr32 Eq_2100) ptrArg04, Stack (ptr32 ci16) ptrArg08, Stack Eq_3 wArg0C, Stack Eq_3 wArg0E)
// Called from:
//      fn0800_019F
Eq_3 fn0800_3632(Eq_3 si, Eq_3 di, union Eq_2100 * ptrArg04, ci16 * ptrArg08, Eq_3 wArg0C, Eq_3 wArg0E)
{
	Eq_3 wArg0A_504 = SLICE(ptrArg08, word16, 16);
	Eq_3 wArg08_506 = (word16) ptrArg08;
	Mem33[0800:9B91:word16] = Mem21[0EFE:2A14:word16] + (Mem21[0EFE:2A12:word16] + 0x20 >>u 0x04);
	Mem34[0800:9B8F:word16] = 0x00;
	mp16 sp_108 = fp - 0x10;
	Eq_3 ds_20 = seg0800;
	Eq_2096 wLoc04_493 = 0x00;
	if (*ptrArg04 == 0x00)
	{
		while (wLoc04_493 < Mem42[0800:9C56:word16] && *ptrArg04 == 0x00)
		{
			struct Eq_2177 Eq_3::* ax_55 = (word16) (wLoc04_493 *32 0x1A);
			if (((seg0800->*ax_55).w9C6A | (seg0800->*ax_55).w9C6C) != 0x00)
			{
				struct Eq_2195 Eq_3::* ax_66 = (word16) (wLoc04_493 *32 0x1A);
				ci16 ax_74;
				(seg0800->*ax_66).ptr9C6A();
				if (ax_74 >= 0x00)
				{
					Mem92[0800:9BEE:word16] = wLoc04_493;
					*ptrArg04 = (union Eq_2100 *) ((word16) wLoc04_493 + 0x0080);
					*ptrArg08 = ax_74;
					break;
				}
			}
			wLoc04_493 = (word16) wLoc04_493 + 1;
		}
	}
	struct Eq_2103 Eq_2106::* sp_109 = sp_108 - 2;
	(ss->*sp_109).t0000 = wArg0A_504;
	(ss->*sp_109).tFFFFFFFE = wArg08_506;
	(ss->*sp_109).tFFFFFFFC = SLICE(ptrArg04, word16, 16);
	(ss->*sp_109).tFFFFFFFA = (word16) ptrArg04;
	&(ss->*sp_109).tFFFFFFF8.u0->t0000 = seg0800;
	(ss->*sp_109).tFFFFFFF6.u0 = ~0x6411;
	fn0800_4766((ss->*sp_109).tFFFFFFF6, (ss->*sp_109).tFFFFFFFA, (ss->*sp_109).tFFFFFFFE);
	struct Eq_2143 Eq_2106::* sp_135 = (char *) &sp_109->t0000 + 2;
	if (*ptrArg04 < 0x00)
	{
		Mem462[0800:9C06:word16] = ~0x01;
		*ptrArg04 = (union Eq_2100 *) ~0x01;
	}
	else
	{
		Mem145[0800:9BF0:word16] = Mem125[ptrArg08 + 0x00:word16];
		if ((wArg0C | wArg0E) == 0x00)
			Mem206[0800:9A0E:byte] = 0x00;
		else
		{
			&(ss->*sp_109).t0000.u0->t0000 = seg0800;
			&(ss->*sp_109).tFFFFFFFE.u0->t0000 = 0x9A0E;
			(ss->*sp_109).tFFFFFFFC = wArg0E;
			(ss->*sp_109).tFFFFFFFA = wArg0C;
			fn0800_2D00((ss->*sp_109).tFFFFFFFA, (ss->*sp_109).tFFFFFFFE);
			if (Mem161[0800:9A0E:byte] != 0x00)
			{
				&(ss->*sp_109).t0000.u0->t0000 = seg0800;
				&(ss->*sp_109).tFFFFFFFE.u0->t0000 = 0x9A0E;
				fn0800_2D63((ss->*sp_109).tFFFFFFFE);
				struct Eq_1976 * dx_ax_588 = (struct Eq_1976 *) <invalid>;
				if (dx_ax_588->bFFFFFFFF != 0x3A && dx_ax_588->bFFFFFFFF != 0x5C)
				{
					dx_ax_588->b0000 = 0x5C;
					dx_ax_588->b0001 = 0x00;
				}
			}
		}
		if (*ptrArg04 > 0x80)
			Mem220[0800:9BEE:word16] = Mem209[ptrArg04 + 0x00:word16] & 0x7F;
		struct Eq_2281 Eq_2106::* sp_226 = sp_108 - 2;
		Mem228[ss:sp_226 + 0x00:word16] = Mem222[0800:9BEE:word16];
		&(ss->*sp_226).tFFFFFFFE.u0->t0000 = seg0800;
		&(ss->*sp_226).tFFFFFFFC.u0->t0000 = 0x9A0E;
		sp_135 = (struct Eq_2143 Eq_2106::*) ((char *) &sp_226->t0000 + 2);
		if (fn0800_3454(seg0800, (ss->*sp_226).tFFFFFFFC, (ss->*sp_226).t0000) == 0x00)
			Mem461[ptrArg04 + 0x00:word16] = Mem233[0800:9C06:word16];
		else
		{
			(ss->*sp_226).t0000 = si;
			(ss->*sp_226).tFFFFFFFE = di;
			&(ss->*sp_226).tFFFFFFFC.u0->t0000 = seg0800;
			Eq_3 es_260 = (ss->*sp_226).tFFFFFFFC;
			word16 di_263 = ~0x6455;
			word16 cx_265;
			for (cx_265 = 0x3F; cx_265 != 0x00; --cx_265)
			{
				es_260->*di_263 = 0x00;
				++di_263;
			}
			(ss->*sp_226).t0000 = *((word32) es_260 + 39519);
			(ss->*sp_226).tFFFFFFFE = es_260;
			&(ss->*sp_226).tFFFFFFFC.u0->t0000 = ~0x6449;
			ds_20 = es_260;
			if (fn0800_3010(es_260, (ss->*sp_226).tFFFFFFFC, (ss->*sp_226).t0000) != 0x00)
			{
				*((word32) es_260 + 39942) = ~0x04;
				*ptrArg04 = (union Eq_2100 *) ~0x04;
				(ss->*sp_226).t0000 = *((word32) es_260 + 39930);
				(ss->*sp_226).tFFFFFFFE = es_260;
				&(ss->*sp_226).tFFFFFFFC.u0->t0000 = 39926;
				fn0800_3042(es_260, (ss->*sp_226).tFFFFFFFC, (ss->*sp_226).t0000);
				sp_135 = (struct Eq_2143 Eq_2106::*) ((char *) &sp_226->t0000 + 2);
			}
			else
			{
				struct Eq_2370 Eq_2106::* sp_336;
				*((word32) es_260 + 0x00009BAB) = 0x00;
				*((word32) es_260 + 0x00009BC0) = 0x00;
				Eq_2377 es_bx_304 = *((word32) es_260 + 0x00009BB6);
				struct Eq_2380 * es_305 = SLICE(es_bx_304, selector, 16);
				*((word32) es_260 + 39934) = es_305;
				word16 bx_307 = (word16) es_bx_304;
				*((word32) es_260 + 39932) = bx_307;
				*((word32) es_260 + 39890) = es_305;
				*((word32) es_260 + 39888) = bx_307;
				Eq_3 ax_311 = *((word32) es_260 + 39519);
				*((word32) es_260 + 0x00009BBA) = ax_311;
				*((word32) es_260 + 39892) = ax_311;
				*((word32) es_260 + 39878) = es_260;
				*((word32) es_260 + 0x00009BC4) = 0x9C06;
				if (*((word32) es_260 + 0x00009BE9) != 0x00)
				{
					(ss->*sp_226).t0000 = es_260;
					&(ss->*sp_226).tFFFFFFFE.u0->t0000 = ~0x6455;
					fn0800_4573((ss->*sp_226).tFFFFFFFE);
					sp_336 = (struct Eq_2370 Eq_2106::*) ((char *) &sp_226->t0000 + 2);
				}
				else
				{
					(ss->*sp_226).t0000 = es_260;
					&(ss->*sp_226).tFFFFFFFE.u0->t0000 = ~0x6455;
					fn0800_456E(es_260, (ss->*sp_226).tFFFFFFFE);
					sp_336 = (struct Eq_2370 Eq_2106::*) ((char *) &sp_226->t0000 + 0x0000FFFE);
				}
				struct Eq_2470 Eq_2106::* sp_357 = sp_336 - 2;
				&(ss->*sp_357).t0000.u0->t0000 = 0x13;
				Eq_3 ax_362 = *((word32) es_260 + 0x00009C0C);
				(ss->*sp_357).tFFFFFFFE = *((word32) es_260 + 39950);
				(ss->*sp_357).tFFFFFFFC = ax_362;
				(ss->*sp_357).tFFFFFFFA = es_260;
				&(ss->*sp_357).tFFFFFFF8.u0->t0000 = ~0x6468;
				fn0800_2E45((ss->*sp_357).tFFFFFFF8, (ss->*sp_357).tFFFFFFFC, (ss->*sp_357).t0000);
				(ss->*sp_357).t0000 = es_260;
				&(ss->*sp_357).tFFFFFFFE.u0->t0000 = ~0x6455;
				fn0800_480A((ss->*sp_357).tFFFFFFFE);
				sp_135 = (struct Eq_2143 Eq_2106::*) ((char *) &sp_357->t0000 + 2);
				if (*((word32) es_260 + 0x00009B97) == 0x00)
				{
					*((word32) es_260 + 39916) = ~0x6455;
					Mem396[es_260:39914:word16] = ~0x6468;
					*((word32) es_260 + 39940) = fn0800_4AA0();
					*((word32) es_260 + 0x00009C00) = *((word32) es_260 + 0x00009BA5);
					*((word32) es_260 + 39938) = 10000;
					*((word32) es_260 + 0x00009BE9) = 0x03;
					*((word32) es_260 + 0x00009C19) = 0x03;
					fn0800_3542();
					*((word32) es_260 + 39942) = 0x00;
					return (ss->*sp_135).t0000;
				}
				*((word32) es_260 + 39942) = (uint16) *((word32) es_260 + 0x00009B97);
			}
		}
	}
	fn0800_3359(ds_20);
	return (ss->*sp_135).t0000;
}

// 0800:3AD4: void fn0800_3AD4()
// Called from:
//      fn0800_3B02
void fn0800_3AD4()
{
	fn0800_4619();
	if ((Mem7[0800:9BF2:word16] | Mem7[0800:9BF4:word16]) == 0x00)
	{
		ptr32 es_bx_22 = Mem7[0800:9B8F:segptr32];
		Mem24[0800:9BF4:word16] = SLICE(es_bx_22, selector, 16);
		Mem26[0800:9BF2:word16] = SLICE(es_bx_22, word16, 0);
		Mem27[0800:9B91:word16] = 0x0800;
		Mem28[0800:9B8F:word16] = 12268;
	}
}

// 0800:3B02: void fn0800_3B02()
// Called from:
//      fn0800_01CE
void fn0800_3B02()
{
	if (Mem13[0800:9BE9:byte] == 0x00)
		Mem123[0800:9C06:word16] = ~0x00;
	else
	{
		Mem18[0800:9BE9:byte] = 0x00;
		fn0800_3AD4();
		fn0800_3042(seg0800, 0800:9BFC, Mem18[0800:9A5F:word16]);
		if ((Mem33[0800:9BF6:word16] | Mem33[0800:9BF8:word16]) != 0x00)
		{
			fn0800_3042(seg0800, 0800:9BF6, Mem33[0800:9BFA:word16]);
			word16 ax_71 = SLICE(Mem56[0800:9BEE:word16] *u32 0x1A, word16, 0);
			(seg0800->*ax_71).w9C70 = 0x00;
			(seg0800->*ax_71).w9C6E = 0x00;
		}
		fn0800_3359(seg0800);
		cup16 di_119;
		word16 si_121 = 39523;
		for (di_119 = 0x00; di_119 < 0x14; ++di_119)
		{
			if ((seg0800->*si_121).b000A != 0x00 && (seg0800->*si_121).w0008 != 0x00)
			{
				fn0800_3042(seg0800, &&(seg0800->*(seg0800->*si_121).w0000), (seg0800->*si_121).w0008);
				(seg0800->*si_121).w0002 = 0x00;
				(seg0800->*si_121).w0000 = 0x00;
				(seg0800->*si_121).w0006 = 0x00;
				(seg0800->*si_121).w0004 = 0x00;
				&(seg0800->*si_121).w0008.u0->t0000 = 0x00;
			}
			++si_121;
		}
	}
}

// 0800:3BBE: void fn0800_3BBE(Stack wchar_t wArg04, Stack wchar_t wArg06, Stack wchar_t wArg08, Stack wchar_t wArg0A, Stack word16 wArg0C)
// Called from:
//      fn0800_0215
//      fn0800_0635
//      fn0800_3542
void fn0800_3BBE(wchar_t wArg04, wchar_t wArg06, wchar_t wArg08, wchar_t wArg0A, word16 wArg0C)
{
	if (wArg04 >= 0x00 && wArg06 >= 0x00)
	{
		word16 bx_30 = Mem17[0800:9BEA:word16];
		if ((seg0800->*bx_30).w0002 >= wArg08 && ((seg0800->*bx_30).w0004 >= wArg0A && (wArg08 >= wArg04 && wArg0A >= wArg06)))
		{
			Mem43[0800:9C1F:word16] = wArg04;
			Mem44[0800:9C21:word16] = wArg06;
			Mem46[0800:9C23:word16] = wArg08;
			Mem48[0800:9C25:word16] = wArg0A;
			Mem50[0800:9C27:word16] = wArg0C;
			fn0800_45B7(wArg04, wArg06, wArg08, wArg0A, (byte) wArg0C);
			fn0800_3CCF(0x00, 0x00);
			return;
		}
	}
	Mem87[0800:9C06:word16] = ~0x0A;
}

// 0800:3CCF: void fn0800_3CCF(Stack word16 wArg04, Stack word16 wArg06)
// Called from:
//      fn0800_3542
//      fn0800_3BBE
void fn0800_3CCF(word16 wArg04, word16 wArg06)
{
	fn0800_4846(wArg04, wArg06);
	Mem27[0800:9C15:word16] = wArg04;
	Mem29[0800:9C17:word16] = wArg06;
}

// 0800:3E06: void fn0800_3E06(Stack cup16 wArg04, Stack word16 wArg06, Stack cup16 wArg08)
// Called from:
//      fn0800_3542
void fn0800_3E06(cup16 wArg04, word16 wArg06, cup16 wArg08)
{
	if (wArg04 <= 0x04 && wArg08 <= 0x03)
	{
		Mem26[0800:9C29:word16] = wArg04;
		Mem28[0800:9C2B:word16] = wArg06;
		Mem29[0800:9C2D:word16] = wArg08;
		fn0800_4B3B(wArg04, wArg06, (byte) wArg08);
	}
	else
		Mem47[0800:9C06:word16] = ~0x0A;
}

// 0800:3EBA: void fn0800_3EBA(Stack cup16 wArg04, Stack cup16 wArg06)
// Called from:
//      fn0800_05E9
//      fn0800_06F3
//      fn0800_0ADF
//      fn0800_0B33
//      fn0800_3542
void fn0800_3EBA(cup16 wArg04, cup16 wArg06)
{
	if (wArg04 > 11)
		Mem33[0800:9C06:word16] = ~0x0A;
	else
	{
		Mem20[0800:9C2F:word16] = wArg04;
		Mem22[0800:9C31:word16] = wArg06;
		fn0800_4BA9((byte) wArg04, (byte) wArg06);
	}
}

// 0800:3F0B: void fn0800_3F0B(Stack segptr32 ptrArg04, Stack cup16 wArg08)
// Called from:
//      fn0800_3542
void fn0800_3F0B(segptr32 ptrArg04, cup16 wArg08)
{
	if (fn0800_4A2C() < wArg08)
		Mem75[0800:9C06:word16] = ~0x0A;
	else
	{
		Mem28[0800:9C2F:word16] = 0x0C;
		Mem30[0800:9C31:word16] = wArg08;
		struct Eq_2774 * ds_87 = SLICE(ptrArg04, selector, 16);
		byte Eq_2774::* si_67 = (word16) ptrArg04;
		word16 di_38 = 0x9C33;
		word16 cx_39;
		for (cx_39 = 0x08; cx_39 != 0x00; --cx_39)
		{
			seg0800->*di_38 = ds_87->*si_67;
			++si_67;
			++di_38;
		}
		fn0800_46C4(ptrArg04, (byte) wArg08);
	}
}

// 0800:403B: void fn0800_403B(Stack Eq_2069 wArg04)
// Called from:
//      fn0800_3542
void fn0800_403B(Eq_2069 wArg04)
{
	byte bArg04_51 = (byte) wArg04;
	if (wArg04 <= 0x0F)
	{
		Mem17[0800:9C12:byte] = bArg04_51;
		if (wArg04 == 0x00)
			Mem23[0800:9C3C:byte] = 0x00;
		else
			Mem22[0800:9C3C:byte] = Mem17[0x0800:wArg04 + 39996:byte];
		fn0800_4ABC(SLICE(CONVERT(Mem25[0800:9C3C:byte], byte, int16), byte, 0));
	}
}

// 0800:408F: void fn0800_408F(Stack (ptr32 Eq_1991) ptrArg04)
// Called from:
//      fn0800_3542
void fn0800_408F(struct Eq_1991 * ptrArg04)
{
	if (Mem25[0800:9C19:word16] != 0x00)
	{
		Eq_2833 ax_38;
		if (ptrArg04->b0000 > 0x10)
			ax_38.u0 = 0x10;
		else
			ax_38.u1 = (uint16) ptrArg04->b0000;
		Eq_2833 wLoc1C_160 = 0x00;
		while (true)
		{
			struct Eq_2846 Eq_2849::* wLoc18_164 = (word16) ptrArg04;
			if (wLoc1C_160 >= ax_38)
				break;
			struct Eq_2849 * es_54 = SLICE(ptrArg04, selector, 16);
			if (Mem47[es_54:SLICE(ptrArg04, word16, 0) + wLoc1C_160 + 0x01:byte] > ~0x00)
				Mem63[0x0800:wLoc1C_160 + 39996:byte] = Mem47[es_54:wLoc18_164 + wLoc1C_160 + 0x01:byte];
			wLoc1C_160 = (word16) wLoc1C_160 + 1;
		}
		if (ptrArg04->b0001 != ~0x00)
			Mem75[0800:9C12:byte] = 0x00;
		word16 si_128 = 39995;
		byte Eq_2886::* di_131 = fp - 0x14;
		word16 cx_100;
		for (cx_100 = 0x11; cx_100 != 0x00; --cx_100)
		{
			ss->*di_131 = seg0800->*si_128;
			++si_128;
			++di_131;
		}
		fn0800_4B20(fp - 0x14);
	}
}

// 0800:41C5: void fn0800_41C5(Stack Eq_222 wArg04, Stack ci16 wArg06, Stack (ptr32 Eq_224) ptrArg08, Stack Eq_225 bArg0C)
// Called from:
//      fn0800_0267
void fn0800_41C5(Eq_222 wArg04, ci16 wArg06, struct Eq_224 * ptrArg08, Eq_225 bArg0C)
{
	cup16 ax_24 = ptrArg08->w0000;
	cup16 si_26 = ptrArg08->w0002;
	word16 si_32 = Mem25[0x0800:Mem25[0800:9BEA:word16] + 0x04:word16] - (wArg06 + Mem25[0800:9C21:word16]);
	if (si_32 > si_26)
		si_32 = si_26;
	if (wArg04 + Mem25[0800:9C1F:word16] + ax_24 <=u Mem25[0x0800:Mem25[0800:9BEA:word16] + 0x02:word16] && (wArg04 + Mem25[0800:9C1F:word16] >= 0x00 && (Test(UGE,false) && wArg06 + Mem25[0800:9C21:word16] >= 0x00)))
	{
		ptrArg08->w0002 = si_32;
		fn0800_4D52(wArg04, wArg06, ptrArg08, (byte) wArg0C);
		ptrArg08->w0002 = si_26;
	}
}

// 0800:42B5: void fn0800_42B5(Stack ci16 wArg04, Stack ci16 wArg06)
// Called from:
//      fn0800_0215
//      fn0800_0635
//      fn0800_3542
void fn0800_42B5(ci16 wArg04, ci16 wArg06)
{
	if (wArg04 >= 0x00 && (wArg04 <= 0x02 && (wArg06 >= 0x00 && wArg06 <= 0x02)))
	{
		Mem34[0800:9C52:word16] = wArg04;
		Mem35[0800:9C54:word16] = wArg06;
		fn0800_46F7((byte) wArg04, (byte) wArg06);
	}
	else
		Mem47[0800:9C06:word16] = ~0x0A;
}

// 0800:42F6: Register (ptr16 Eq_2983) fn0800_42F6(Stack Eq_162 wArg04, Stack word16 wArg06, Stack word16 wArg08)
// Called from:
//      fn0800_0215
//      fn0800_0635
//      fn0800_3542
struct Eq_2983 * fn0800_42F6(Eq_162 wArg04, word16 wArg06, word16 wArg08)
{
	Eq_162 si_21 = wArg04;
	if (Mem18[0x0800:Mem18[0800:9BEA:word16] + 0x01:byte] == 0x03)
	{
l0800_4496:
		Mem320[0800:9C4C:word16] = si_21;
		Mem328[0800:9C4E:word16] = wArg06;
		Mem330[0800:9C50:word16] = wArg08;
		return fn0800_4C0F((byte) si_21, (byte) wArg06, (byte) wArg08);
	}
	si_21 = wArg04;
	if (wArg04 == 0x00)
		goto l0800_4496;
	si_21 = wArg04;
	if (wArg04 >= 0x00 && wArg04 <= Mem18[0800:9A61:word16])
	{
		if (wArg04 == Mem18[0800:9C4C:word16])
			goto l0800_4496;
		struct Eq_3022 Eq_3::* ax_41 = (word16) ((wArg04 - 0x01) *32 0x0F);
		if (wArg04 == Mem18[0800:9C1D:word16])
		{
l0800_447C:
			Eq_3043 es_bx_301 = (seg0800->*ax_41).t9A67;
			Mem303[0800:9C0A:word16] = SLICE(es_bx_301, selector, 16);
			Mem305[0800:9C08:word16] = SLICE(es_bx_301, word16, 0);
			goto l0800_4496;
		}
		if (Mem18[0x0800:SLICE((Mem18[0800:9C1D:word16] - 0x01) *u32 0x0F, word16, 0) + 39531:word16] != 0x00)
		{
			word16 ax_58 = SLICE((Mem18[0800:9C1D:word16] - 0x01) *u32 0x0F, word16, 0);
			fn0800_3042(seg0800, &(seg0800->*&ax_58->w9A63), (seg0800->*ax_58).t9A6B);
			(seg0800->*ax_58).w9A65 = 0x00;
			(seg0800->*ax_58).w9A63 = 0x00;
			(seg0800->*ax_58).w9A69 = 0x00;
			(seg0800->*ax_58).w9A67 = 0x00;
			&(seg0800->*ax_58).t9A6B.u0->t0000 = 0x00;
		}
		if (((seg0800->*ax_41).t9A67 | (seg0800->*ax_41).w9A69) != 0x00)
		{
l0800_4478:
			Mem296[0800:9C1D:word16] = wArg04;
			goto l0800_447C;
		}
		fn0800_2D7E(0800:A048, SEQ(0x0800, ax_41 + 39533), 0800:99F8);
		if (fn0800_33E3(seg0800, fp - 0x0E, 0800:99F8, 0800:9A0E) != 0x00)
		{
			if (Mem140[0800:9C06:word16] == ~0x02)
				Mem293[0800:9C06:word16] = ~0x07;
		}
		else if (fn0800_3010(seg0800, fp - 0x0C, wLoc0E + 0x10) != 0x00)
		{
			fn0800_2DBC();
			Mem290[0800:9C06:word16] = ~0x08;
		}
		else
		{
			word16 dx_184 = wLoc0A + (wLoc0C + 0x0F >> 0x04);
			if (fn0800_2E0C(seg0800) != 0x00)
				fn0800_3042(seg0800, fp - 0x0C, wLoc0E + 0x10);
			else
			{
				fn0800_2DBC();
				if (fn0800_3172(SEQ(dx_184, 0x00)) == wArg04)
				{
					(seg0800->*ax_41).w9A65 = wLoc0A;
					(seg0800->*ax_41).w9A63 = wLoc0C;
					(seg0800->*ax_41).w9A6B = wLoc0E + 0x10;
					goto l0800_4478;
				}
				fn0800_3042(seg0800, fp - 0x0C, wLoc0E + 0x10);
				Mem266[0800:9C06:word16] = ~0x0C;
			}
		}
	}
	else
		Mem307[0800:9C06:word16] = ~0x0D;
	si_21.u0 = 0x00;
	wArg08 = 0x01;
	goto l0800_4496;
}

// 0800:4515: void fn0800_4515()
// Called from:
//      fn0800_46A1
void fn0800_4515()
{
}

// 0800:4518: void fn0800_4518(Register (ptr16 Eq_3187) ds)
// Called from:
//      fn0800_480A
void fn0800_4518(struct Eq_3187 * ds)
{
	if (ds->bA057 != ~0x00)
		return;
	if (ds->b99F6 != 0xA5)
	{
		byte ah_11;
		byte bh_12;
		ds->bA057 = bios_video_get_current_video_mode(out ah_11, out bh_12);
		byte al_18 = 0040:0010;
		ds->bA058 = al_18;
		if (ds->bA050 != 0x05 && ds->bA050 != 0x07)
			0040:0010 = (byte *) (al_18 & ~0x30 | 0x20);
	}
	else
		ds->bA057 = 0x00;
}

// 0800:456E: void fn0800_456E(Register Eq_3 ds, Stack Eq_3 ptrArg04)
// Called from:
//      fn0800_3632
void fn0800_456E(Eq_3 ds, Eq_3 ptrArg04)
{
	*((word32) ds + 41047) = ~0x00;
	fn0800_4573(ptrArg04);
}

// 0800:4573: void fn0800_4573(Stack Eq_3 ptrArg04)
// Called from:
//      fn0800_3632
//      fn0800_456E
void fn0800_4573(Eq_3 ptrArg04)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->bA050 != 0x05;
	struct Eq_3241 * es_31 = SLICE(ptrArg04, selector, 16);
	if (*((word32) ptrArg04 + 22) == 0x00)
		es_31 = ds_12->ptr9B95;
	word16 bx_54;
	ds_12->ptr9B8F();
	ds_12->w9C0C = bx_54;
	ds_12->ptr9C0E = es_31;
}

// 0800:45B7: void fn0800_45B7(Stack wchar_t wArg04, Stack wchar_t wArg06, Stack wchar_t wArg08, Stack wchar_t wArg0A, Stack byte bArg0C)
// Called from:
//      fn0800_3BBE
void fn0800_45B7(wchar_t wArg04, wchar_t wArg06, wchar_t wArg08, wchar_t wArg0A, byte bArg0C)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->ptr9B8F();
}

// 0800:4619: void fn0800_4619()
// Called from:
//      fn0800_3AD4
void fn0800_4619()
{
	selector ds_12 = Mem11[0800:019D:selector];
	if (ds_12->bA057 != ~0x00)
	{
		word16 ax_23;
		word16 bx_24;
		ds_12->ptr9B8F();
		if (ds_12->b99F6 != 0xA5)
		{
			0040:0010 = (byte *) ds_12->bA058;
			bios_video_set_mode(ds_12->bA057);
		}
	}
	ds_12->bA057 = ~0x00;
}

// 0800:46A1: void fn0800_46A1(Stack byte bArg04)
// Called from:
//      fn0800_3542
void fn0800_46A1(byte bArg04)
{
	uint16 ax_24 = (uint16) bArg04;
	Mem25[Mem11[0800:019D:selector]:39823:ptr32]();
	fn0800_4515();
}

// 0800:46C4: void fn0800_46C4(Stack segptr32 ptrArg04, Stack byte bArg08)
// Called from:
//      fn0800_3F0B
void fn0800_46C4(segptr32 ptrArg04, byte bArg08)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->b9C11 = bArg08;
	ds_12->ptr9B8F();
	ds_12->b9C14 = 0x0C;
	ds_12->ptr9B8F();
}

// 0800:46F7: void fn0800_46F7(Stack byte bArg04, Stack byte bArg06)
// Called from:
//      fn0800_42B5
void fn0800_46F7(byte bArg04, byte bArg06)
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:4766: void fn0800_4766(Stack Eq_2124 ptrArg04, Stack Eq_3 ptrArg08, Stack Eq_3 ptrArg0C)
// Called from:
//      fn0800_3632
void fn0800_4766(Eq_2124 ptrArg04, Eq_3 ptrArg08, Eq_3 ptrArg0C)
{
	byte al_50;
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->bA04E = ~0x00;
	ds_12->bA04F = 0x00;
	ds_12->bA051 = 0x0A;
	ci8 al_25 = *ptrArg08;
	ds_12->bA050 = al_25;
	if (al_25 == 0x00)
	{
		fn0800_47E8(&(ss->*((char *) fp + 2)), ds_12);
		al_50 = ds_12->bA04E;
	}
	else
	{
		ds_12->bA04F = (ci8) *ptrArg0C;
		ci8 bl_39 = *ptrArg08;
		if (bl_39 < 0x00)
			return;
		Eq_3365 bx_47 = (uint16) bl_39;
		ds_12->bA051 = seg0800->*((word16) bx_47 + 0x00004D91);
		al_50 = seg0800->*((word16) bx_47 + 19829);
		ds_12->bA04E = al_50;
	}
	*ptrArg04 = (uint16) al_50;
}

// 0800:47E8: void fn0800_47E8(Sequence (ptr32 Eq_3351) ss_bp, Register (ptr16 Eq_3318) ds)
// Called from:
//      fn0800_4766
void fn0800_47E8(struct Eq_3351 * ss_bp, struct Eq_3318 * ds)
{
	fn0800_4D9F(ds);
	ci8 al_22 = ds->bA050;
	uint16 * es_di_21 = ss_bp->ptr0006;
	uint16 ax_27 = (uint16) al_22;
	if (al_22 == ~0x00)
		ax_27 = SEQ(al_22, al_22);
	*es_di_21 = ax_27;
	*ss_bp->ptr000A = (uint16) ds->bA04F;
}

// 0800:480A: void fn0800_480A(Stack Eq_3 ptrArg04)
// Called from:
//      fn0800_3632
void fn0800_480A(Eq_3 ptrArg04)
{
	selector ds_12 = Mem11[0800:019D:selector];
	fn0800_4518(ds_12);
	word16 bx_27 = (word16) ptrArg04;
	ds_12->wA053 = bx_27;
	ds_12->ptrA055 = SLICE(ptrArg04, selector, 16);
	ds_12->ptr9B8F();
}

// 0800:4846: void fn0800_4846(Stack word16 wArg04, Stack word16 wArg06)
// Called from:
//      fn0800_3CCF
void fn0800_4846(word16 wArg04, word16 wArg06)
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:48E3: void fn0800_48E3(Stack word16 wArg04, Stack word16 wArg06, Stack word16 wArg08, Stack word16 wArg0A)
// Called from:
//      fn0800_05E9
//      fn0800_06F3
//      fn0800_0ADF
//      fn0800_0B33
void fn0800_48E3(word16 wArg04, word16 wArg06, word16 wArg08, word16 wArg0A)
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:4A0B: void fn0800_4A0B(Stack byte bArg04)
// Called from:
//      fn0800_0215
//      fn0800_0635
//      fn0800_3542
void fn0800_4A0B(byte bArg04)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->b9C10 = bArg04;
	ds_12->ptr9B8F();
}

// 0800:4A2C: Register word16 fn0800_4A2C()
// Called from:
//      fn0800_3542
//      fn0800_3F0B
word16 fn0800_4A2C()
{
	word16 cx_25;
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
	return cx_25;
}

// 0800:4A47: Register word16 fn0800_4A47()
// Called from:
//      fn0800_3542
word16 fn0800_4A47()
{
	word16 bx_25;
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
	return bx_25;
}

// 0800:4A62: void fn0800_4A62()
// Called from:
//      fn0800_3542
void fn0800_4A62()
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:4AA0: Register word16 fn0800_4AA0()
// Called from:
//      fn0800_3632
word16 fn0800_4AA0()
{
	word16 cx_23;
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
	return cx_23 - 0x01;
}

// 0800:4ABC: void fn0800_4ABC(Stack byte bArg04)
// Called from:
//      fn0800_403B
void fn0800_4ABC(byte bArg04)
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:4B20: void fn0800_4B20(Stack Eq_2885 ptrArg04)
// Called from:
//      fn0800_408F
void fn0800_4B20(Eq_2885 ptrArg04)
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:4B3B: void fn0800_4B3B(Stack cup16 wArg04, Stack word16 wArg06, Stack byte bArg08)
// Called from:
//      fn0800_3E06
void fn0800_4B3B(cup16 wArg04, word16 wArg06, byte bArg08)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->b9C13 = (byte) wArg04;
	ds_12->bA052 = bArg08;
	ds_12->ptr9B8F();
}

// 0800:4BA9: void fn0800_4BA9(Stack byte bArg04, Stack byte bArg06)
// Called from:
//      fn0800_3EBA
void fn0800_4BA9(byte bArg04, byte bArg06)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->b9C11 = bArg06;
	ds_12->ptr9B8F();
	ds_12->b9C14 = bArg04;
	ds_12->ptr9B8F();
}

// 0800:4BD9: void fn0800_4BD9(Stack word16 wArg04, Stack wchar_t wArg06, Stack segptr32 ptrArg08)
// Called from:
//      fn0800_0215
//      fn0800_0635
void fn0800_4BD9(word16 wArg04, wchar_t wArg06, segptr32 ptrArg08)
{
	selector ds_12 = Mem11[0800:019D:selector];
	ds_12->ptr9B8F();
	byte Eq_3495::* bx_29 = (word16) ptrArg08;
	struct Eq_3495 * es_79 = SLICE(ptrArg08, selector, 16);
	byte Eq_3495::* di_110 = bx_29;
	word16 cx_34 = ~0x00;
	while (cx_34 != 0x00)
	{
		++di_110;
		--cx_34;
		if (es_79->*di_110 != 0x00)
			break;
	}
	ds_12->ptr9B8F();
}

// 0800:4C0F: Register (ptr16 Eq_3513) fn0800_4C0F(Stack byte bArg04, Stack byte bArg06, Stack byte bArg08)
// Called from:
//      fn0800_42F6
struct Eq_3513 * fn0800_4C0F(byte bArg04, byte bArg06, byte bArg08)
{
	selector ds_12 = Mem11[0800:019D:selector];
	struct Eq_3513 * es_20 = ds_12->ptr9C0E;
	if (bArg04 != 0x00)
	{
		struct Eq_3524 * es_di_39 = ds_12->ptr9C0C;
		es_20 = SLICE(es_di_39, selector, 16);
		es_di_39->b0001 == 0x03;
	}
	ds_12->ptr9B8F();
	return es_20;
}

// 0800:4D52: void fn0800_4D52(Stack Eq_222 wArg04, Stack ci16 wArg06, Stack (ptr32 Eq_224) ptrArg08, Stack byte bArg0C)
// Called from:
//      fn0800_41C5
void fn0800_4D52(Eq_222 wArg04, ci16 wArg06, struct Eq_224 * ptrArg08, byte bArg0C)
{
	Mem18[Mem11[0800:019D:selector]:39823:ptr32]();
}

// 0800:4D9F: void fn0800_4D9F(Register (ptr16 Eq_3318) ds)
// Called from:
//      fn0800_47E8
void fn0800_4D9F(struct Eq_3318 * ds)
{
	ds->bA04E = ~0x00;
	ds->bA050 = ~0x00;
	ds->bA04F = 0x00;
	fn0800_4DD5(ds);
	ci8 bl_18 = ds->bA050;
	if (bl_18 != ~0x00)
	{
		Eq_3555 bx_24 = (uint16) bl_18;
		ds->bA04E = seg0800->*((word16) bx_24 + 19829);
		ds->bA04F = seg0800->*((word16) bx_24 + 0x00004D83);
		ds->bA051 = seg0800->*((word16) bx_24 + 0x00004D91);
	}
}

// 0800:4DD5: void fn0800_4DD5(Register (ptr16 Eq_3318) ds)
// Called from:
//      fn0800_4D9F
void fn0800_4DD5(struct Eq_3318 * ds)
{
	word16 cx_155;
	word16 bx_81;
	byte ah_5;
	byte bh_6;
	if (bios_video_get_current_video_mode(out ah_5, out bh_6) != 0x07)
	{
		if (!fn0800_4ECA())
		{
			ds->bA050 = 0x06;
			return;
		}
		word16 cx_161 = <invalid>;
		bx_81 = bx_154;
		cx_155 = cx_161;
		byte cl_163;
		word16 bx_154;
		if (fn0800_4E3C(out cl_163, out bx_154))
		{
			if (fn0800_4EFF() == 0x00)
			{
				ds->bA050 = 0x01;
				if (!fn0800_4EA9())
					ds->bA050 = 0x02;
				return;
			}
			else
			{
				ds->bA050 = 0x0A;
				return;
			}
		}
	}
	else
	{
		word16 cx_160 = <invalid>;
		bx_81 = bx_153;
		cx_155 = cx_160;
		byte cl_162;
		word16 bx_153;
		if (!fn0800_4E3C(out cl_162, out bx_153))
		{
			if ((byte) (uint16) fn0800_4ECD() == 0x00)
			{
				word16 ax_37 = ~B800:0000;
				B800:0000 = (word16 *) ~B800:0000;
				if (ax_37 == B800:0000)
					ds->bA050 = 0x01;
				return;
			}
			else
			{
				ds->bA050 = 0x07;
				return;
			}
		}
	}
	fn0800_4E5A((byte) cx_155, bx_81, ds);
}

// 0800:4E3C: FlagGroup bool fn0800_4E3C(Register out Eq_3591 clOut, Register out Eq_3591 bxOut)
// Called from:
//      fn0800_4DD5
bool fn0800_4E3C(union Eq_3591 & clOut, union Eq_3591 & bxOut)
{
	ci8 bl_7;
	byte ch_8;
	ci8 cl_9;
	ci8 bh_10 = bios_video_get_EGA_info(out bl_7, out ch_8, out cl_9);
	if (cl_9 >= 0x0C || (bh_10 > 0x01 || bl_7 > 0x03))
	{
		clOut.u1 = <invalid>;
		bxOut.u1 = <invalid>;
		return false;
	}
	else
	{
		clOut.u1 = <invalid>;
		bxOut.u1 = <invalid>;
		return true;
	}
}

// 0800:4E5A: void fn0800_4E5A(Register cu8 cl, Register word16 bx, Register (ptr16 Eq_3318) ds)
// Called from:
//      fn0800_4DD5
void fn0800_4E5A(cu8 cl, word16 bx, struct Eq_3318 * ds)
{
	byte bh = SLICE(bx, byte, 8);
	byte bl = (byte) bx;
	ds->bA050 = 0x04;
	if (bh == 0x01)
		ds->bA050 = 0x05;
	else if (!fn0800_4E9A(cl) && bl != 0x00)
	{
		ds->bA050 = 0x03;
		if (fn0800_4EA9() || C000:0039 == 0x345A && C000:003B == 14644)
			ds->bA050 = 0x09;
	}
}

// 0800:4E9A: FlagGroup bool fn0800_4E9A(Register cu8 cl)
// Called from:
//      fn0800_4E5A
bool fn0800_4E9A(cu8 cl)
{
	bool C_11 = SLICE(cond(cl - 0x02), bool, 1);
	if (cl >= 0x02)
	{
		C_11 = !SLICE(cond(cl - 0x06), bool, 1);
		if (cl >= 0x06)
			C_11 = SLICE(cond(cl - 0x08), bool, 1);
	}
	return C_11;
}

// 0800:4EA9: FlagGroup bool fn0800_4EA9()
// Called from:
//      fn0800_4DD5
//      fn0800_4E5A
bool fn0800_4EA9()
{
	byte bh_5;
	cu8 bl_6 = bios_video_get_DAC_color_page_state(out bh_5);
	if (true || bl_6 != 0x07 && (bl_6 != 0x08 && (bl_6 < 11 || bl_6 > 0x0C)))
		return false;
	return true;
}

// 0800:4ECA: FlagGroup bool fn0800_4ECA()
// Called from:
//      fn0800_4DD5
bool fn0800_4ECA()
{
	return false;
}

// 0800:4ECD: Register byte fn0800_4ECD()
// Called from:
//      fn0800_4DD5
byte fn0800_4ECD()
{
	cu8 bl_18 = 0x00;
	byte al_6 = __inb(0x03BA);
	word16 cx_11;
	for (cx_11 = 0x8000; cx_11 != 0x00; --cx_11)
	{
		if ((__inb(0x03BA) & 0x80) != (al_6 & 0x80))
		{
			++bl_18;
			if (bl_18 >= 0x0A)
			{
				word16 cx_22;
				for (cx_22 = 0x8000; cx_22 != 0x00; --cx_22)
				{
					if ((__inb(0x03BA) & 0x30) != 0x10)
						return 0x01;
				}
				return 0x02;
			}
		}
	}
	return 0x00;
}

// 0800:4EFF: Register word16 fn0800_4EFF()
// Called from:
//      fn0800_4DD5
word16 fn0800_4EFF()
{
	bios_video_unknown_1030();
	if (false)
	{
		byte al_19 = 0000:0002;
		if ((al_19 == 0x00 || al_19 == 0x02) && (__inb(0x0188) & 0x04) != 0x00)
			return 0x01;
	}
	return 0x00;
}

// 0800:6880: void fn0800_6880(Register Eq_3817 ds, Stack Eq_3817 wArg02)
// Called from:
//      fn0800_6E01
void fn0800_6880(Eq_3817 ds, Eq_3817 wArg02)
{
	Eq_3819 si_17;
	Eq_3817 si_13 = wArg02;
	if (wArg02 >= 0x00)
	{
		if (wArg02 <= 88)
			goto l0800_6893;
	}
	else
	{
		si_17 = -wArg02;
		if (si_17 <= 0x23)
		{
			((word16) ds + 0x0000A05A)->u0 = ~0x00;
l0800_68AC:
			*((word16) ds + 0x00006FF6) = si_17;
			return;
		}
	}
	si_13.u0 = 0x57;
l0800_6893:
	*((word16) ds + 0x0000A05A) = si_13;
	si_17.u1 = (int16) (ds->*((word16) si_13 + 0x0000A05C));
	goto l0800_68AC;
}

// 0800:68BC: Register Eq_3 fn0800_68BC(Register Eq_3 ds, Stack word16 wArg02)
// Called from:
//      fn0800_0100
//      fn0800_6D94
Eq_3 fn0800_68BC(Eq_3 ds, word16 wArg02)
{
	while (true)
	{
		ui16 ax_11 = *((word32) ds + 0x0000A0C0);
		--*((word32) ds + 0x0000A0C0);
		if (ax_11 == 0x00)
			break;
		ui16 bx_18 = *((word32) ds + 0x0000A0C0);
		SEQ(0x0800, SEQ(ds, 41858)[bx_18 * 0x02])();
	}
	(seg0800->**((word32) ds + 41142))();
	(seg0800->**((word32) ds + 41144))();
	(seg0800->**((word32) ds + 0x0000A0BA))();
	return fn0800_018D();
}

// 0800:6911: void fn0800_6911(Register Eq_3 ds, Stack Eq_3874 wArg02)
// Called from:
//      fn0800_69F0
//      fn0800_6C8F
//      fn0800_6CC6
void fn0800_6911(Eq_3 ds, Eq_3874 wArg02)
{
	Eq_3874 ax_17 = ds->*((word16) wArg02 + 6);
	*((word32) ds + 41924) = ax_17;
	if (ax_17 == wArg02)
		((word32) ds + 41924)->u0 = 0x00;
	else
	{
		struct Eq_3882 Eq_3::* si_21 = ds->*((word16) wArg02 + 4);
		ds->*((word32) (*((word32) ds + 41924)) + 4) = si_21;
		(ds->*si_21).t0006 = *((word32) ds + 41924);
	}
}

// 0800:693F: Register (memptr Eq_3 Eq_3899) fn0800_693F(Register Eq_3 ds, Stack Eq_3874 wArg02, Stack Eq_3902 wArg04)
// Called from:
//      fn0800_69F0
struct Eq_3899 Eq_3::* fn0800_693F(Eq_3 ds, Eq_3874 wArg02, Eq_3902 wArg04)
{
	ds->*wArg02 -= wArg04;
	word16 si_21 = Mem19[ds:wArg02 + 0x00:word16] + wArg02;
	ds->*si_21 = (word16) wArg04.u0 + 1;
	ds->*((word16) si_21 + 2) = wArg02;
	if (*((word32) ds + 41922) == wArg02)
		*((word32) ds + 41922) = si_21;
	else
		Mem32[ds:si_21 + wArg04 + 0x02:word16] = si_21;
	return (word16) si_21 + 4;
}

// 0800:6979: Register word16 fn0800_6979(Register Eq_3 ds, Stack Eq_3902 wArg02)
// Called from:
//      fn0800_69F0
word16 fn0800_6979(Eq_3 ds, Eq_3902 wArg02)
{
	word16 ax_43;
	Eq_3874 ax_23 = fn0800_6A82(ds, wArg02, 0x00);
	if (ax_23 == ~0x00)
		ax_43 = 0x00;
	else
	{
		ds->*((word16) ax_23 + 2) = *((word32) ds + 41922);
		ds->*ax_23 = (word16) wArg02 + 1;
		*((word32) ds + 41922) = ax_23;
		ax_43 = (word16) ((word32) *((word32) ds + 41922) + 4);
	}
	return ax_43;
}

// 0800:69B6: Register (memptr Eq_3 Eq_3902) fn0800_69B6(Register Eq_3 ds, Stack Eq_3902 wArg02)
// Called from:
//      fn0800_69F0
union Eq_3902 Eq_3::* fn0800_69B6(Eq_3 ds, Eq_3902 wArg02)
{
	union Eq_3902 Eq_3::* ax_42;
	Eq_3874 ax_23 = fn0800_6A82(ds, wArg02, 0x00);
	if (ax_23 == ~0x00)
		ax_42 = 0x00;
	else
	{
		*((word32) ds + 0x0000A3C6) = ax_23;
		*((word32) ds + 41922) = ax_23;
		ds->*ax_23 = (word16) wArg02 + 1;
		ax_42 = (word16) ax_23 + 4;
	}
	return ax_42;
}

// 0800:69F0: Register (memptr Eq_3 Eq_3987) fn0800_69F0(Register Eq_3 ds, Stack Eq_3 wArg02)
// Called from:
//      fn0800_02F8
//      fn0800_6DAC
struct Eq_3987 Eq_3::* fn0800_69F0(Eq_3 ds, Eq_3 wArg02)
{
	struct Eq_3987 Eq_3::* ax_104;
	if (wArg02 == 0x00)
		ax_104 = 0x00;
	else
	{
		Eq_3902 ax_22 = (word32) wArg02 + 11 & ~0x07;
		if (*((word32) ds + 0x0000A3C6) == 0x00)
			ax_104 = fn0800_69B6(ds, ax_22);
		else
		{
			Eq_3874 si_27 = *((word32) ds + 41924);
			if (si_27 != 0x00)
			{
				do
				{
					if (ds->*si_27 >= (word16) ax_22.u1 + 40)
					{
						ax_104 = fn0800_693F(ds, si_27, ax_22);
						return ax_104;
					}
					if (ds->*si_27 >= ax_22)
					{
						fn0800_6911(ds, si_27);
						ds->*si_27 = (word16) (ds->*si_27) + 1;
						ax_104 = (word16) si_27 + 4;
						return ax_104;
					}
					si_27 = ds->*((word16) si_27 + 6);
				} while (si_27 != *((word32) ds + 41924));
			}
			ax_104 = fn0800_6979(ds, ax_22);
		}
	}
	return ax_104;
}

// 0800:6A5E: void fn0800_6A5E(Register Eq_3 ds, Stack Eq_3874 wArg02)
// Called from:
//      fn0800_6AB6
void fn0800_6A5E(Eq_3 ds, Eq_3874 wArg02)
{
	if (wArg02 < fp - 0x0102)
		*((word32) ds + 28642) = wArg02;
	else
		*((word32) ds + 0x00006FF6) = 0x08;
}

// 0800:6A82: Register Eq_3874 fn0800_6A82(Register Eq_3 ds, Stack Eq_3902 wArg02, Stack word16 wArg04)
// Called from:
//      fn0800_6979
//      fn0800_69B6
Eq_3874 fn0800_6A82(Eq_3 ds, Eq_3902 wArg02, word16 wArg04)
{
	Eq_3874 ax_29;
	word16 ax_12 = wArg02 + Mem7[ds:28642:word16];
	if ((bool) (ax_12 < 0x0100) + ((bool) (ax_12 < 0x00) + wArg04) == 0x00 && (word16) ax_12.u0 + 0x0100 < fp - 2)
	{
		Eq_3874 v13_30 = *((word32) ds + 28642);
		*((word32) ds + 28642) = ax_12;
		ax_29 = v13_30;
	}
	else
	{
		*((word32) ds + 0x00006FF6) = 0x08;
		ax_29.u0 = ~0x00;
	}
	return ax_29;
}

// 0800:6AB6: void fn0800_6AB6(Register Eq_3 ds, Stack Eq_3874 wArg02)
// Called from:
//      fn0800_6CC6
void fn0800_6AB6(Eq_3 ds, Eq_3874 wArg02)
{
	fn0800_6A5E(ds, wArg02);
}

// 0800:6AD6: void fn0800_6AD6(Register Eq_3 ds, Stack byte bArg02, Stack byte bArg04, Stack uint16 wArg06, Stack (memptr Eq_3 byte) wArg08, Stack Eq_463 wArg0A, Stack Eq_4094 wArg0C)
// Called from:
//      fn0800_6B55
void fn0800_6AD6(Eq_3 ds, byte bArg02, byte bArg04, uint16 wArg06, byte Eq_3::* wArg08, Eq_463 wArg0A, Eq_4094 wArg0C)
{
	byte Eq_3::* di_125 = wArg08;
	cu8 bl_28 = (byte) wArg06;
	if (wArg06 > 0x24 || bl_28 < 0x02)
	{
l0800_6B44:
		ds->*di_125 = 0x00;
		return;
	}
	Eq_463 ax_31 = wArg0A;
	Eq_4094 cx_33 = wArg0C;
	if (wArg0C < 0x00 && bArg04 != 0x00)
	{
		ds->*wArg08 = 0x2D;
		ax_31 = -wArg0A;
		di_125 = wArg08 + 1;
		cx_33 = -wArg0C - (ax_31 == 0x00);
	}
	byte Eq_3::* si_107 = fp - 0x24;
	if (cx_33 != 0x00)
	{
		do
		{
			uint32 dx_ax_55 = (uint32) cx_33;
			uint32 dx_ax_63 = SEQ((uint16) (dx_ax_55 % wArg06), ax_31);
			ds->*si_107 = (byte) (uint16) (dx_ax_63 % wArg06);
			Eq_4094 ax_59 = (uint16) (dx_ax_55 /u wArg06);
			cx_33 = ax_59;
			ax_31.u1 = (uint16) (dx_ax_63 /u wArg06);
			++si_107;
		} while (ax_59 != 0x00);
l0800_6B27:
		if (ax_31 == 0x00)
		{
			word16 cx_104 = si_107 + (0x24 - fp);
			do
			{
				byte al_117;
				--si_107;
				cu8 al_111 = ds->*si_107;
				if (al_111 < 0x0A)
					al_117 = al_111 + 0x30;
				else
					al_117 = al_111 - 0x0A + bArg02;
				ds->*di_125 = al_117;
				++di_125;
				--cx_104;
			} while (cx_104 != 0x00);
			goto l0800_6B44;
		}
	}
	uint32 dx_ax_82 = (uint32) ax_31;
	ds->*si_107 = (byte) (uint16) (dx_ax_82 % wArg06);
	ax_31.u1 = (uint16) (dx_ax_82 /u wArg06);
	++si_107;
	goto l0800_6B27;
}

// 0800:6B55: void fn0800_6B55(Register Eq_3 ds, Stack Eq_463 wArg02, Stack (memptr Eq_3 byte) wArg04, Stack uint16 wArg06)
// Called from:
//      fn0800_05E9
void fn0800_6B55(Eq_3 ds, Eq_463 wArg02, byte Eq_3::* wArg04, uint16 wArg06)
{
	Eq_463 ax_11;
	Eq_4094 dx_12;
	if (wArg06 == 0x0A)
	{
		int32 dx_ax_16 = (int32) wArg02;
		dx_12 = SLICE(dx_ax_16, word16, 16);
		ax_11 = (word16) dx_ax_16;
	}
	else
	{
		ax_11 = wArg02;
		dx_12.u0 = 0x00;
	}
	fn0800_6AD6(ds, 0x61, 0x01, wArg06, wArg04, ax_11, dx_12);
}

// 0800:6BC1: Register uint16 fn0800_6BC1(Register uint16 ax, Register uint16 cx, Register uint16 dx, Register uint16 bx, Register out ptr16 dxOut)
// Called from:
//      fn0800_6F53
uint16 fn0800_6BC1(uint16 ax, uint16 cx, uint16 dx, uint16 bx, ptr16 & dxOut)
{
	uint16 ax_15 = dx;
	if (dx != 0x00)
		ax_15 = (word16) (bx *32 dx);
	uint16 cx_28 = ax_15;
	if (cx != 0x00)
		cx_28 = ax_15 + (word16) (ax *32 cx);
	uint32 dx_ax_43 = bx *32 ax;
	dxOut = SLICE(dx_ax_43, word16, 16) + cx_28;
	return (word16) dx_ax_43;
}

// 0800:6BF7: void fn0800_6BF7(Register Eq_3 ds, Stack Eq_197 wArg02, Stack Eq_197 wArg04, Stack cu16 wArg06)
// Called from:
//      fn0800_0267
//      fn0800_111E
void fn0800_6BF7(Eq_3 ds, Eq_197 wArg02, Eq_197 wArg04, cu16 wArg06)
{
	Eq_4225 ax_24;
	if (wArg02 < wArg04)
		ax_24.u0 = 0x01;
	else
		ax_24.u0 = 0x00;
	Eq_197 si_32 = wArg02;
	Eq_197 di_33 = wArg04;
	cu16 cx_34 = wArg06;
	if (ax_24 != 0x00)
	{
		si_32 = (word16) wArg02 + wArg06 - 0x01;
		di_33 = (word16) wArg04 + wArg06 - 0x01;
	}
	if ((di_33 & 0x01) != 0x00)
	{
		if (wArg06 == 0x00)
			return;
		ds->*di_33 = ds->*si_32;
		si_32 = (word16) si_32 + 1;
		di_33 = (word16) di_33 + 1;
		cx_34 = wArg06 - 0x01;
	}
	Eq_4244 si_104 = si_32 - ax_24;
	Eq_4246 di_105 = di_33 - ax_24;
	uint16 cx_70 = cx_34 >> 0x01;
	cx_106 = cx_70;
	while (true)
	{
		uint16 cx_106;
		if (cx_106 == 0x00)
			break;
		ds->*di_105 = ds->*si_104;
		si_104 = (word16) si_104 + 2;
		di_105 = (word16) di_105 + 2;
		--cx_106;
	}
	if (cx_70 < 0x00)
		Mem84[ds:di_105 + ax_24:byte] = Mem81[ds:si_104 + ax_24:byte];
}

// 0800:6C56: void fn0800_6C56(Register Eq_3 ds, Stack Eq_3874 wArg02)
// Called from:
//      fn0800_6D1F
void fn0800_6C56(Eq_3 ds, Eq_3874 wArg02)
{
	if (*((word32) ds + 41924) != 0x00)
	{
		Eq_3874 di_23 = ds->*((word32) (*((word32) ds + 41924)) + 6);
		ds->*((word32) (*((word32) ds + 41924)) + 6) = wArg02;
		ds->*((word16) di_23 + 4) = wArg02;
		ds->*((word16) wArg02 + 6) = di_23;
		ds->*((word16) wArg02 + 4) = *((word32) ds + 41924);
	}
	else
	{
		*((word32) ds + 41924) = wArg02;
		ds->*((word16) wArg02 + 4) = wArg02;
		ds->*((word16) wArg02 + 6) = wArg02;
	}
}

// 0800:6C8F: void fn0800_6C8F(Register Eq_3 ds, Stack Eq_3874 wArg02, Stack Eq_3874 wArg04)
// Called from:
//      fn0800_6D1F
void fn0800_6C8F(Eq_3 ds, Eq_3874 wArg02, Eq_3874 wArg04)
{
	ds->*wArg02 += ds->*wArg04;
	if (*((word32) ds + 41922) == wArg04)
		*((word32) ds + 41922) = wArg02;
	else
		(word16) wArg04 + ds->*wArg04 + 0x02 = wArg02;
	fn0800_6911(ds, wArg04);
}

// 0800:6CC6: void fn0800_6CC6(Register Eq_3 ds)
// Called from:
//      fn0800_6D6D
void fn0800_6CC6(Eq_3 ds)
{
	if (*((word32) ds + 0x0000A3C6) == *((word32) ds + 41922))
	{
		fn0800_6AB6(ds, *((word32) ds + 0x0000A3C6));
		((word32) ds + 41922)->u0 = 0x00;
		((word32) ds + 0x0000A3C6)->u0 = 0x00;
	}
	else
	{
		Eq_3874 si_13 = ds->*((word32) (*((word32) ds + 41922)) + 2);
		if ((ds->*si_13 & 0x01) == 0x00)
		{
			fn0800_6911(ds, si_13);
			if (si_13 == *((word32) ds + 0x0000A3C6))
			{
				((word32) ds + 41922)->u0 = 0x00;
				((word32) ds + 0x0000A3C6)->u0 = 0x00;
			}
			else
				*((word32) ds + 41922) = ds->*((word16) si_13 + 2);
			fn0800_6AB6(ds, si_13);
		}
		else
		{
			fn0800_6AB6(ds, *((word32) ds + 41922));
			*((word32) ds + 41922) = si_13;
		}
	}
}

// 0800:6D1F: void fn0800_6D1F(Register Eq_3 ds, Stack Eq_3874 wArg02)
// Called from:
//      fn0800_6D6D
void fn0800_6D1F(Eq_3 ds, Eq_3874 wArg02)
{
	--ds->*wArg02;
	Eq_3874 si_16 = wArg02;
	Eq_3874 ax_21 = (word16) wArg02 + ds->*wArg02;
	Eq_3874 di_23 = ds->*((word16) wArg02 + 2);
	if ((ds->*di_23 & 0x01) == 0x00 && wArg02 != *((word32) ds + 0x0000A3C6))
	{
		ds->*di_23 += ds->*wArg02;
		ds->*((word16) ax_21 + 2) = di_23;
		si_16 = di_23;
	}
	else
		fn0800_6C56(ds, wArg02);
	if ((ds->*ax_21 & 0x01) == 0x00)
		fn0800_6C8F(ds, si_16, ax_21);
}

// 0800:6D6D: void fn0800_6D6D(Register Eq_3 ds, Stack Eq_241 wArg02)
// Called from:
//      fn0800_02D6
//      fn0800_6DA0
void fn0800_6D6D(Eq_3 ds, Eq_241 wArg02)
{
	if (wArg02 != 0x00)
	{
		if ((word16) wArg02 + 0x0000FFFC == *((word32) ds + 41922))
			fn0800_6CC6(ds);
		else
			fn0800_6D1F(ds, (word16) wArg02 + 0x0000FFFC);
	}
}

// 0800:6D94: Register Eq_3 fn0800_6D94(Register Eq_3 ds, Stack word16 wArg04)
// Called from:
//      fn0800_2FEC
Eq_3 fn0800_6D94(Eq_3 ds, word16 wArg04)
{
	return fn0800_68BC(ds, wArg04);
}

// 0800:6DA0: void fn0800_6DA0(Register Eq_3 ds, Stack Eq_241 wArg04)
// Called from:
//      fn0800_3042
void fn0800_6DA0(Eq_3 ds, Eq_241 wArg04)
{
	fn0800_6D6D(ds, wArg04);
}

// 0800:6DAC: Register Eq_241 fn0800_6DAC(Register Eq_3 ds, Stack Eq_3 wArg04, Register out Eq_3 dxOut)
// Called from:
//      fn0800_3010
Eq_241 fn0800_6DAC(Eq_3 ds, Eq_3 wArg04, union Eq_3 & dxOut)
{
	Eq_241 ax_13 = fn0800_69F0(ds, wArg04);
	dxOut = ds;
	return ax_13;
}

// 0800:6DBC: void fn0800_6DBC(Stack (memptr (ptr16 Eq_4483) Eq_127) wArg02)
// Called from:
//      fn0800_01CE
void fn0800_6DBC(<type-error> Eq_4483::* wArg02)
{
	fn0800_30B4(wArg02);
}

// 0800:6DDA: Register word16 fn0800_6DDA(Register (ptr16 Eq_328) es, Register Eq_3 ds, Stack word16 wArg02, Stack (memptr Eq_3 Eq_340) wArg04, Stack (memptr Eq_3 Eq_341) wArg06, Register out ptr16 diOut, Register out (ptr16 Eq_343) dsOut)
// Called from:
//      fn0800_03CD
word16 fn0800_6DDA(struct Eq_328 * es, Eq_3 ds, word16 wArg02, struct Eq_340 Eq_3::* wArg04, struct Eq_341 Eq_3::* wArg06, ptr16 & diOut, struct Eq_343 & dsOut)
{
	fn0800_6F96(es, ds, fp - 0x0A);
	ptr16 di_34;
	struct Eq_343 * ds_35;
	word16 si_38 = fn0800_6E01(ds, wArg02, wArg04, wArg06, fp - 0x0A, out di_34, out ds_35);
	diOut = di_34;
	dsOut = ds_35;
	return si_38;
}

// 0800:6E01: Register word16 fn0800_6E01(Register Eq_3 ds, Stack word16 wArg02, Stack (memptr Eq_3 Eq_340) wArg04, Stack (memptr Eq_3 Eq_341) wArg06, Stack (memptr Eq_3 Eq_4505) wArg08, Register out ptr16 diOut, Register out Eq_3817 dsOut)
// Called from:
//      fn0800_6DDA
word16 fn0800_6E01(Eq_3 ds, word16 wArg02, struct Eq_340 Eq_3::* wArg04, struct Eq_341 Eq_3::* wArg06, struct Eq_4505 Eq_3::* wArg08, ptr16 & diOut, union Eq_3817 & dsOut)
{
	cu8 al_25 = (byte) wArg02;
	<anonymous> * ptrLoc10_146 = fp - 0x0C;
	word16 v14_41 = (ds->*wArg08).w0000;
	word16 v15_45 = (ds->*wArg08).w0006;
	struct Eq_4532 Eq_4517::* sp_60;
	word16 cx_61;
	Eq_3817 ax_62;
	word16 bx_63;
	word16 dx_64;
	Eq_3817 SCZDOP_66;
	ptrLoc10_146();
	word16 di_53 = (ds->*wArg04).w000A;
	word16 si_54 = (ds->*wArg04).w0008;
	(ss->*sp_60).tFFFFFFFE = SCZDOP_66;
	(ss->*sp_60).tFFFFFFFC = SCZDOP_66;
	(ss->*sp_60).wFFFFFFFA = si_54;
	(ss->*sp_60).wFFFFFFF8 = v15_45;
	(ss->*sp_60).wFFFFFFF6 = v14_41;
	(ds->*wArg08).w0000 = (ss->*sp_60).wFFFFFFF6;
	(ds->*wArg08).w0006 = (ss->*sp_60).wFFFFFFF8;
	(ds->*wArg06).w0008 = (ss->*sp_60).wFFFFFFFA;
	(ds->*wArg06).t000E = (ss->*sp_60).tFFFFFFFC;
	(ds->*wArg06).t000C = (ss->*sp_60).tFFFFFFFE;
	(ds->*wArg06).t000C &= 0x01;
	(ds->*wArg06).w000A = di_53;
	(ds->*wArg06).w0006 = dx_64;
	(ds->*wArg06).w0004 = cx_61;
	(ds->*wArg06).w0002 = bx_63;
	(ds->*wArg06).t0000 = ax_62;
	Eq_3817 ds_99 = (ss->*sp_60).t0000;
	if ((ds->*wArg06).t000C != 0x00)
	{
		(ss->*sp_60).t0000 = ax_62;
		(ss->*sp_60).tFFFFFFFE = ax_62;
		fn0800_6880(ds_99, (ss->*sp_60).tFFFFFFFE);
	}
	word16 si_119 = (ss->*sp_60).w0004;
	diOut = (ss->*sp_60).ptr0002;
	dsOut = ds_99;
	return si_119;
}

// 0800:6F53: Register cui16 fn0800_6F53(Register Eq_3 ds)
// Called from:
//      fn0800_111E
cui16 fn0800_6F53(Eq_3 ds)
{
	word16 dx_12;
	cup16 ax_10 = fn0800_6BC1(*((word32) ds + 41154), 0x015A, *((word32) ds + 41156), 20021, out dx_12);
	*((word32) ds + 41156) = (uint16) ((bool) (ax_10 < 0x01) + dx_12);
	*((word32) ds + 41154) = ax_10 + 0x01;
	cui16 ax_24 = *((word32) ds + 41156) & 0x7FFF;
	return ax_24;
}

// 0800:6F96: void fn0800_6F96(Register (ptr16 Eq_328) es, Register Eq_3 ds, Stack (memptr Eq_3 Eq_4491) wArg02)
// Called from:
//      fn0800_6DDA
void fn0800_6F96(struct Eq_328 * es, Eq_3 ds, struct Eq_4491 Eq_3::* wArg02)
{
	(ds->*wArg02).ptr0000 = es;
	(ds->*wArg02).ptr0002 = cs;
	(ds->*wArg02).ptr0004 = ss;
	(ds->*wArg02).t0006 = ds;
}

// 0800:6FAB: void fn0800_6FAB(Stack Eq_652 wArg02)
// Called from:
//      fn0800_06F3
//      fn0800_0B33
void fn0800_6FAB(Eq_652 wArg02)
{
	if (wArg02 > 0x12)
	{
		uint16 ax_17 = (uint16) (1193181 /u wArg02);
		byte bl_28 = (byte) ax_17;
		byte bh_31 = SLICE(ax_17, byte, 8);
		byte al_19 = __inb(0x61);
		if ((al_19 & 0x03) == 0x00)
		{
			__outb(0x61, al_19 | 0x03);
			__outb(0x43, ~0x49);
		}
		__outb(66, bl_28);
		__outb(66, bh_31);
	}
}

// 0800:6FD7: void fn0800_6FD7()
// Called from:
//      fn0800_06F3
//      fn0800_0B33
//      fn0800_0BDC
void fn0800_6FD7()
{
	__outb(0x61, __inb(0x61) & 252);
}

